use gvdb::gresource::GResourceBuilder;

const PREFIX: &str = "/relm4/icons/scalable/actions/";
const ICONS: &str = "icons";
const TARGET_FILE: &str = "resources.gresource";

fn main() {
    println!("cargo:rerun-if-changed=icons");

    let ignore_list = vec![
        // AUTOGENERATED - DO NOT EDIT
        #[cfg(not(feature = "about"))]
        "about-symbolic.svg",
        #[cfg(not(feature = "address-book-alt"))]
        "address-book-alt-symbolic.svg",
        #[cfg(not(feature = "address-book"))]
        "address-book-symbolic.svg",
        #[cfg(not(feature = "airbrush-tool"))]
        "airbrush-tool-symbolic.svg",
        #[cfg(not(feature = "alarm"))]
        "alarm-symbolic.svg",
        #[cfg(not(feature = "align-tool"))]
        "align-tool-symbolic.svg",
        #[cfg(not(feature = "anniversary"))]
        "anniversary-symbolic.svg",
        #[cfg(not(feature = "annotation-sidebar"))]
        "annotation-sidebar-symbolic.svg",
        #[cfg(not(feature = "app-icon-design"))]
        "app-icon-design-symbolic.svg",
        #[cfg(not(feature = "application-x-firmware"))]
        "application-x-firmware-symbolic.svg",
        #[cfg(not(feature = "archive"))]
        "archive-symbolic.svg",
        #[cfg(not(feature = "arrow1-down"))]
        "arrow1-down-symbolic.svg",
        #[cfg(not(feature = "arrow1-left"))]
        "arrow1-left-symbolic.svg",
        #[cfg(not(feature = "arrow1-right"))]
        "arrow1-right-symbolic.svg",
        #[cfg(not(feature = "arrow1-up"))]
        "arrow1-up-symbolic.svg",
        #[cfg(not(feature = "arrow2-bottom-left"))]
        "arrow2-bottom-left-symbolic.svg",
        #[cfg(not(feature = "arrow2-bottom-right"))]
        "arrow2-bottom-right-symbolic.svg",
        #[cfg(not(feature = "arrow2-down"))]
        "arrow2-down-symbolic.svg",
        #[cfg(not(feature = "arrow2-left"))]
        "arrow2-left-symbolic.svg",
        #[cfg(not(feature = "arrow2-right"))]
        "arrow2-right-symbolic.svg",
        #[cfg(not(feature = "arrow2-top-left"))]
        "arrow2-top-left-symbolic.svg",
        #[cfg(not(feature = "arrow2-top-right"))]
        "arrow2-top-right-symbolic.svg",
        #[cfg(not(feature = "arrow2-up"))]
        "arrow2-up-symbolic.svg",
        #[cfg(not(feature = "arrow3-down"))]
        "arrow3-down-symbolic.svg",
        #[cfg(not(feature = "arrow3-left"))]
        "arrow3-left-symbolic.svg",
        #[cfg(not(feature = "arrow3-right"))]
        "arrow3-right-symbolic.svg",
        #[cfg(not(feature = "arrow3-up"))]
        "arrow3-up-symbolic.svg",
        #[cfg(not(feature = "arrow-into-box"))]
        "arrow-into-box-symbolic.svg",
        #[cfg(not(feature = "arrows-questionmark"))]
        "arrows-questionmark-symbolic.svg",
        #[cfg(not(feature = "assistive-listening"))]
        "assistive-listening-symbolic.svg",
        #[cfg(not(feature = "attach-audio"))]
        "attach-audio-symbolic.svg",
        #[cfg(not(feature = "audio-only"))]
        "audio-only-symbolic.svg",
        #[cfg(not(feature = "audio-x-generic"))]
        "audio-x-generic-symbolic.svg",
        #[cfg(not(feature = "auth-otp"))]
        "auth-otp-symbolic.svg",
        #[cfg(not(feature = "axes-four-quadrants"))]
        "axes-four-quadrants-symbolic.svg",
        #[cfg(not(feature = "axes-one-quadrant"))]
        "axes-one-quadrant-symbolic.svg",
        #[cfg(not(feature = "axis-log-horizontal"))]
        "axis-log-horizontal-symbolic.svg",
        #[cfg(not(feature = "axis-log-vertical"))]
        "axis-log-vertical-symbolic.svg",
        #[cfg(not(feature = "background-app-ghost"))]
        "background-app-ghost-symbolic.svg",
        #[cfg(not(feature = "background-app-rectangular"))]
        "background-app-rectangular-symbolic.svg",
        #[cfg(not(feature = "background-app-sleepyface"))]
        "background-app-sleepyface-symbolic.svg",
        #[cfg(not(feature = "background-app"))]
        "background-app-symbolic.svg",
        #[cfg(not(feature = "bank"))]
        "bank-symbolic.svg",
        #[cfg(not(feature = "banner"))]
        "banner-symbolic.svg",
        #[cfg(not(feature = "barbecue"))]
        "barbecue-symbolic.svg",
        #[cfg(not(feature = "baseball"))]
        "baseball-symbolic.svg",
        #[cfg(not(feature = "battery"))]
        "battery-symbolic.svg",
        #[cfg(not(feature = "bear"))]
        "bear-symbolic.svg",
        #[cfg(not(feature = "bed"))]
        "bed-symbolic.svg",
        #[cfg(not(feature = "bell-large-none"))]
        "bell-large-none-symbolic.svg",
        #[cfg(not(feature = "bell-large"))]
        "bell-large-symbolic.svg",
        #[cfg(not(feature = "bell-none"))]
        "bell-none-symbolic.svg",
        #[cfg(not(feature = "bell-outline-none"))]
        "bell-outline-none-symbolic.svg",
        #[cfg(not(feature = "bell-outline"))]
        "bell-outline-symbolic.svg",
        #[cfg(not(feature = "bell"))]
        "bell-symbolic.svg",
        #[cfg(not(feature = "bench"))]
        "bench-symbolic.svg",
        #[cfg(not(feature = "big-dot"))]
        "big-dot-symbolic.svg",
        #[cfg(not(feature = "big-x"))]
        "big-x-symbolic.svg",
        #[cfg(not(feature = "birthday"))]
        "birthday-symbolic.svg",
        #[cfg(not(feature = "blend-tool"))]
        "blend-tool-symbolic.svg",
        #[cfg(not(feature = "blind"))]
        "blind-symbolic.svg",
        #[cfg(not(feature = "bluetooth-none"))]
        "bluetooth-none-symbolic.svg",
        #[cfg(not(feature = "bluetooth"))]
        "bluetooth-symbolic.svg",
        #[cfg(not(feature = "blur-alt"))]
        "blur-alt-symbolic.svg",
        #[cfg(not(feature = "blur"))]
        "blur-symbolic.svg",
        #[cfg(not(feature = "body"))]
        "body-symbolic.svg",
        #[cfg(not(feature = "bottom-large"))]
        "bottom-large-symbolic.svg",
        #[cfg(not(feature = "bottom"))]
        "bottom-symbolic.svg",
        #[cfg(not(feature = "box-down"))]
        "box-down-symbolic.svg",
        #[cfg(not(feature = "box-left"))]
        "box-left-symbolic.svg",
        #[cfg(not(feature = "box-right"))]
        "box-right-symbolic.svg",
        #[cfg(not(feature = "box-up"))]
        "box-up-symbolic.svg",
        #[cfg(not(feature = "branch"))]
        "branch-symbolic.svg",
        #[cfg(not(feature = "bread"))]
        "bread-symbolic.svg",
        #[cfg(not(feature = "break-point"))]
        "break-point-symbolic.svg",
        #[cfg(not(feature = "briefcase"))]
        "briefcase-symbolic.svg",
        #[cfg(not(feature = "broken-camera-inverse"))]
        "broken-camera-inverse-symbolic.svg",
        #[cfg(not(feature = "broken-playback"))]
        "broken-playback-symbolic.svg",
        #[cfg(not(feature = "broken-video"))]
        "broken-video-symbolic.svg",
        #[cfg(not(feature = "brush-monitor"))]
        "brush-monitor-symbolic.svg",
        #[cfg(not(feature = "brush"))]
        "brush-symbolic.svg",
        #[cfg(not(feature = "bug"))]
        "bug-symbolic.svg",
        #[cfg(not(feature = "build-alt"))]
        "build-alt-symbolic.svg",
        #[cfg(not(feature = "build-configure"))]
        "build-configure-symbolic.svg",
        #[cfg(not(feature = "building"))]
        "building-symbolic.svg",
        #[cfg(not(feature = "build"))]
        "build-symbolic.svg",
        #[cfg(not(feature = "bus"))]
        "bus-symbolic.svg",
        #[cfg(not(feature = "cafe"))]
        "cafe-symbolic.svg",
        #[cfg(not(feature = "cage"))]
        "cage-symbolic.svg",
        #[cfg(not(feature = "call-add"))]
        "call-add-symbolic.svg",
        #[cfg(not(feature = "call-incoming"))]
        "call-incoming-symbolic.svg",
        #[cfg(not(feature = "call-made"))]
        "call-made-symbolic.svg",
        #[cfg(not(feature = "call-merge"))]
        "call-merge-symbolic.svg",
        #[cfg(not(feature = "call-missed-incoming"))]
        "call-missed-incoming-symbolic.svg",
        #[cfg(not(feature = "call-missed-outgoing"))]
        "call-missed-outgoing-symbolic.svg",
        #[cfg(not(feature = "call-missed"))]
        "call-missed-symbolic.svg",
        #[cfg(not(feature = "call-outgoing"))]
        "call-outgoing-symbolic.svg",
        #[cfg(not(feature = "call-outgoing-unsuccessful"))]
        "call-outgoing-unsuccessful-symbolic.svg",
        #[cfg(not(feature = "call-received"))]
        "call-received-symbolic.svg",
        #[cfg(not(feature = "call-ringer-silenced"))]
        "call-ringer-silenced-symbolic.svg",
        #[cfg(not(feature = "call-ring"))]
        "call-ring-symbolic.svg",
        #[cfg(not(feature = "call-split"))]
        "call-split-symbolic.svg",
        #[cfg(not(feature = "camera-broken"))]
        "camera-broken-symbolic.svg",
        #[cfg(not(feature = "camera-dead"))]
        "camera-dead-symbolic.svg",
        #[cfg(not(feature = "camera-flash-auto"))]
        "camera-flash-auto-symbolic.svg",
        #[cfg(not(feature = "camera-flash-disabled"))]
        "camera-flash-disabled-symbolic.svg",
        #[cfg(not(feature = "camera-flash"))]
        "camera-flash-symbolic.svg",
        #[cfg(not(feature = "camera-focus"))]
        "camera-focus-symbolic.svg",
        #[cfg(not(feature = "camera-grid"))]
        "camera-grid-symbolic.svg",
        #[cfg(not(feature = "camera-iso-alt"))]
        "camera-iso-alt-symbolic.svg",
        #[cfg(not(feature = "camera-iso"))]
        "camera-iso-symbolic.svg",
        #[cfg(not(feature = "camera-large"))]
        "camera-large-symbolic.svg",
        #[cfg(not(feature = "camera-shutter"))]
        "camera-shutter-symbolic.svg",
        #[cfg(not(feature = "cameras"))]
        "cameras-symbolic.svg",
        #[cfg(not(feature = "camera-static-inverse"))]
        "camera-static-inverse-symbolic.svg",
        #[cfg(not(feature = "camera-static"))]
        "camera-static-symbolic.svg",
        #[cfg(not(feature = "camera"))]
        "camera-symbolic.svg",
        #[cfg(not(feature = "camera-toggle"))]
        "camera-toggle-symbolic.svg",
        #[cfg(not(feature = "carousel"))]
        "carousel-symbolic.svg",
        #[cfg(not(feature = "cat-sleeping"))]
        "cat-sleeping-symbolic.svg",
        #[cfg(not(feature = "cat"))]
        "cat-symbolic.svg",
        #[cfg(not(feature = "cd"))]
        "cd-symbolic.svg",
        #[cfg(not(feature = "center"))]
        "center-symbolic.svg",
        #[cfg(not(feature = "chain-link-loose"))]
        "chain-link-loose-symbolic.svg",
        #[cfg(not(feature = "chain-link"))]
        "chain-link-symbolic.svg",
        #[cfg(not(feature = "charge"))]
        "charge-symbolic.svg",
        #[cfg(not(feature = "chat-bubble-emtpy"))]
        "chat-bubble-emtpy-symbolic.svg",
        #[cfg(not(feature = "chat-bubbles-empty-inverted"))]
        "chat-bubbles-empty-inverted-symbolic.svg",
        #[cfg(not(feature = "chat-bubbles-emtpy"))]
        "chat-bubbles-emtpy-symbolic.svg",
        #[cfg(not(feature = "chat-bubbles-text-inverted"))]
        "chat-bubbles-text-inverted-symbolic.svg",
        #[cfg(not(feature = "chat-bubbles-text"))]
        "chat-bubbles-text-symbolic.svg",
        #[cfg(not(feature = "chat-bubble-text-inverted"))]
        "chat-bubble-text-inverted-symbolic.svg",
        #[cfg(not(feature = "chat-bubble-text"))]
        "chat-bubble-text-symbolic.svg",
        #[cfg(not(feature = "chat-none"))]
        "chat-none-symbolic.svg",
        #[cfg(not(feature = "chat"))]
        "chat-symbolic.svg",
        #[cfg(not(feature = "checkerboard-big"))]
        "checkerboard-big-symbolic.svg",
        #[cfg(not(feature = "checkerboard"))]
        "checkerboard-symbolic.svg",
        #[cfg(not(feature = "checkmark-large"))]
        "checkmark-large-symbolic.svg",
        #[cfg(not(feature = "checkmark-small"))]
        "checkmark-small-symbolic.svg",
        #[cfg(not(feature = "checkmark"))]
        "checkmark-symbolic.svg",
        #[cfg(not(feature = "check-plain"))]
        "check-plain-symbolic.svg",
        #[cfg(not(feature = "check-round-outline2"))]
        "check-round-outline2-symbolic.svg",
        #[cfg(not(feature = "check-round-outline"))]
        "check-round-outline-symbolic.svg",
        #[cfg(not(feature = "check-round-outline-whole"))]
        "check-round-outline-whole-symbolic.svg",
        #[cfg(not(feature = "christmas"))]
        "christmas-symbolic.svg",
        #[cfg(not(feature = "cigarette-none"))]
        "cigarette-none-symbolic.svg",
        #[cfg(not(feature = "cigarette"))]
        "cigarette-symbolic.svg",
        #[cfg(not(feature = "circle-filled"))]
        "circle-filled-symbolic.svg",
        #[cfg(not(feature = "circle-outline-thick"))]
        "circle-outline-thick-symbolic.svg",
        #[cfg(not(feature = "circle-outline-thin"))]
        "circle-outline-thin-symbolic.svg",
        #[cfg(not(feature = "city"))]
        "city-symbolic.svg",
        #[cfg(not(feature = "clipboard"))]
        "clipboard-symbolic.svg",
        #[cfg(not(feature = "clock-alt"))]
        "clock-alt-symbolic.svg",
        #[cfg(not(feature = "clock"))]
        "clock-symbolic.svg",
        #[cfg(not(feature = "closed-captioning"))]
        "closed-captioning-symbolic.svg",
        #[cfg(not(feature = "cloud-disabled"))]
        "cloud-disabled-symbolic.svg",
        #[cfg(not(feature = "cloud-filled"))]
        "cloud-filled-symbolic.svg",
        #[cfg(not(feature = "cloud-outline-thick"))]
        "cloud-outline-thick-symbolic.svg",
        #[cfg(not(feature = "cloud-outline-thin"))]
        "cloud-outline-thin-symbolic.svg",
        #[cfg(not(feature = "clouds-outline"))]
        "clouds-outline-symbolic.svg",
        #[cfg(not(feature = "clouds"))]
        "clouds-symbolic.svg",
        #[cfg(not(feature = "cocktail"))]
        "cocktail-symbolic.svg",
        #[cfg(not(feature = "code"))]
        "code-symbolic.svg",
        #[cfg(not(feature = "coin"))]
        "coin-symbolic.svg",
        #[cfg(not(feature = "colorimeter-colorhug"))]
        "colorimeter-colorhug-symbolic.svg",
        #[cfg(not(feature = "color-picker"))]
        "color-picker-symbolic.svg",
        #[cfg(not(feature = "color"))]
        "color-symbolic.svg",
        #[cfg(not(feature = "columns"))]
        "columns-symbolic.svg",
        #[cfg(not(feature = "compass-alt"))]
        "compass-alt-symbolic.svg",
        #[cfg(not(feature = "compass"))]
        "compass-symbolic.svg",
        #[cfg(not(feature = "compass-wind"))]
        "compass-wind-symbolic.svg",
        #[cfg(not(feature = "computer-chip"))]
        "computer-chip-symbolic.svg",
        #[cfg(not(feature = "computer"))]
        "computer-symbolic.svg",
        #[cfg(not(feature = "configure"))]
        "configure-symbolic.svg",
        #[cfg(not(feature = "container-terminal"))]
        "container-terminal-symbolic.svg",
        #[cfg(not(feature = "controls-big"))]
        "controls-big-symbolic.svg",
        #[cfg(not(feature = "controls"))]
        "controls-symbolic.svg",
        #[cfg(not(feature = "copy"))]
        "copy-symbolic.svg",
        #[cfg(not(feature = "cow"))]
        "cow-symbolic.svg",
        #[cfg(not(feature = "credit-card"))]
        "credit-card-symbolic.svg",
        #[cfg(not(feature = "crop"))]
        "crop-symbolic.svg",
        #[cfg(not(feature = "cross-filled-large"))]
        "cross-filled-large-symbolic.svg",
        #[cfg(not(feature = "cross-filled"))]
        "cross-filled-symbolic.svg",
        #[cfg(not(feature = "cross-large"))]
        "cross-large-symbolic.svg",
        #[cfg(not(feature = "cross"))]
        "cross-symbolic.svg",
        #[cfg(not(feature = "crossword-clue-across"))]
        "crossword-clue-across-symbolic.svg",
        #[cfg(not(feature = "crossword-clue-down"))]
        "crossword-clue-down-symbolic.svg",
        #[cfg(not(feature = "C"))]
        "C-symbolic.svg",
        #[cfg(not(feature = "cut"))]
        "cut-symbolic.svg",
        #[cfg(not(feature = "cycling"))]
        "cycling-symbolic.svg",
        #[cfg(not(feature = "dark-mode"))]
        "dark-mode-symbolic.svg",
        #[cfg(not(feature = "deaf"))]
        "deaf-symbolic.svg",
        #[cfg(not(feature = "deck"))]
        "deck-symbolic.svg",
        #[cfg(not(feature = "decode"))]
        "decode-symbolic.svg",
        #[cfg(not(feature = "derivative2"))]
        "derivative2-symbolic.svg",
        #[cfg(not(feature = "derivative"))]
        "derivative-symbolic.svg",
        #[cfg(not(feature = "detach-audio"))]
        "detach-audio-symbolic.svg",
        #[cfg(not(feature = "diagnostics"))]
        "diagnostics-symbolic.svg",
        #[cfg(not(feature = "dialog"))]
        "dialog-symbolic.svg",
        #[cfg(not(feature = "dialpad"))]
        "dialpad-symbolic.svg",
        #[cfg(not(feature = "diamond-filled"))]
        "diamond-filled-symbolic.svg",
        #[cfg(not(feature = "diamond-outline-thick"))]
        "diamond-outline-thick-symbolic.svg",
        #[cfg(not(feature = "diamond-outline-thin"))]
        "diamond-outline-thin-symbolic.svg",
        #[cfg(not(feature = "dice2"))]
        "dice2-symbolic.svg",
        #[cfg(not(feature = "dice3"))]
        "dice3-symbolic.svg",
        #[cfg(not(feature = "dice"))]
        "dice-symbolic.svg",
        #[cfg(not(feature = "dictionary"))]
        "dictionary-symbolic.svg",
        #[cfg(not(feature = "discover"))]
        "discover-symbolic.svg",
        #[cfg(not(feature = "display-projector"))]
        "display-projector-symbolic.svg",
        #[cfg(not(feature = "display"))]
        "display-symbolic.svg",
        #[cfg(not(feature = "display-with-window"))]
        "display-with-window-symbolic.svg",
        #[cfg(not(feature = "dock-bottom"))]
        "dock-bottom-symbolic.svg",
        #[cfg(not(feature = "dock-left"))]
        "dock-left-symbolic.svg",
        #[cfg(not(feature = "dock-right"))]
        "dock-right-symbolic.svg",
        #[cfg(not(feature = "dock"))]
        "dock-symbolic.svg",
        #[cfg(not(feature = "dock-top"))]
        "dock-top-symbolic.svg",
        #[cfg(not(feature = "dock-usb"))]
        "dock-usb-symbolic.svg",
        #[cfg(not(feature = "dog"))]
        "dog-symbolic.svg",
        #[cfg(not(feature = "do-not-distrub"))]
        "do-not-distrub-symbolic.svg",
        #[cfg(not(feature = "dot"))]
        "dot-symbolic.svg",
        #[cfg(not(feature = "dotted-box"))]
        "dotted-box-symbolic.svg",
        #[cfg(not(feature = "down-large"))]
        "down-large-symbolic.svg",
        #[cfg(not(feature = "down"))]
        "down-symbolic.svg",
        #[cfg(not(feature = "drag-n-drop"))]
        "drag-n-drop-symbolic.svg",
        #[cfg(not(feature = "drawer"))]
        "drawer-symbolic.svg",
        #[cfg(not(feature = "drinks"))]
        "drinks-symbolic.svg",
        #[cfg(not(feature = "driving"))]
        "driving-symbolic.svg",
        #[cfg(not(feature = "drone"))]
        "drone-symbolic.svg",
        #[cfg(not(feature = "drop-hollow"))]
        "drop-hollow-symbolic.svg",
        #[cfg(not(feature = "earth"))]
        "earth-symbolic.svg",
        #[cfg(not(feature = "editor"))]
        "editor-symbolic.svg",
        #[cfg(not(feature = "edit-select-all"))]
        "edit-select-all-symbolic.svg",
        #[cfg(not(feature = "edit-select-none"))]
        "edit-select-none-symbolic.svg",
        #[cfg(not(feature = "edit"))]
        "edit-symbolic.svg",
        #[cfg(not(feature = "egg"))]
        "egg-symbolic.svg",
        #[cfg(not(feature = "eject-large"))]
        "eject-large-symbolic.svg",
        #[cfg(not(feature = "eject"))]
        "eject-symbolic.svg",
        #[cfg(not(feature = "electric-car"))]
        "electric-car-symbolic.svg",
        #[cfg(not(feature = "encoder-knob"))]
        "encoder-knob-symbolic.svg",
        #[cfg(not(feature = "encode"))]
        "encode-symbolic.svg",
        #[cfg(not(feature = "entry-clear"))]
        "entry-clear-symbolic.svg",
        #[cfg(not(feature = "eraser2"))]
        "eraser2-symbolic.svg",
        #[cfg(not(feature = "eraser3"))]
        "eraser3-symbolic.svg",
        #[cfg(not(feature = "eraser4"))]
        "eraser4-symbolic.svg",
        #[cfg(not(feature = "eraser5"))]
        "eraser5-symbolic.svg",
        #[cfg(not(feature = "eraser"))]
        "eraser-symbolic.svg",
        #[cfg(not(feature = "error"))]
        "error-symbolic.svg",
        #[cfg(not(feature = "execute-from"))]
        "execute-from-symbolic.svg",
        #[cfg(not(feature = "execute-to"))]
        "execute-to-symbolic.svg",
        #[cfg(not(feature = "explore2-large"))]
        "explore2-large-symbolic.svg",
        #[cfg(not(feature = "explore2"))]
        "explore2-symbolic.svg",
        #[cfg(not(feature = "explore"))]
        "explore-symbolic.svg",
        #[cfg(not(feature = "external-devices"))]
        "external-devices-symbolic.svg",
        #[cfg(not(feature = "external-link"))]
        "external-link-symbolic.svg",
        #[cfg(not(feature = "eye-closed-negative"))]
        "eye-closed-negative-symbolic.svg",
        #[cfg(not(feature = "eye-closed"))]
        "eye-closed-symbolic.svg",
        #[cfg(not(feature = "eye-not-looking"))]
        "eye-not-looking-symbolic.svg",
        #[cfg(not(feature = "eye-open-negative-filled"))]
        "eye-open-negative-filled-symbolic.svg",
        #[cfg(not(feature = "eye-open-negative"))]
        "eye-open-negative-symbolic.svg",
        #[cfg(not(feature = "eye-open"))]
        "eye-open-symbolic.svg",
        #[cfg(not(feature = "face-unlock"))]
        "face-unlock-symbolic.svg",
        #[cfg(not(feature = "fast-food"))]
        "fast-food-symbolic.svg",
        #[cfg(not(feature = "fast-fourier-transform"))]
        "fast-fourier-transform-symbolic.svg",
        #[cfg(not(feature = "fax"))]
        "fax-symbolic.svg",
        #[cfg(not(feature = "feet"))]
        "feet-symbolic.svg",
        #[cfg(not(feature = "few-clouds-night"))]
        "few-clouds-night-symbolic.svg",
        #[cfg(not(feature = "few-clouds-outline"))]
        "few-clouds-outline-symbolic.svg",
        #[cfg(not(feature = "few-clouds"))]
        "few-clouds-symbolic.svg",
        #[cfg(not(feature = "file-cabinet"))]
        "file-cabinet-symbolic.svg",
        #[cfg(not(feature = "file-manager"))]
        "file-manager-symbolic.svg",
        #[cfg(not(feature = "fill-tool"))]
        "fill-tool-symbolic.svg",
        #[cfg(not(feature = "fingerprint2"))]
        "fingerprint2-symbolic.svg",
        #[cfg(not(feature = "fingerprint-authentication"))]
        "fingerprint-authentication-symbolic.svg",
        #[cfg(not(feature = "fingerprint"))]
        "fingerprint-symbolic.svg",
        #[cfg(not(feature = "fire2"))]
        "fire2-symbolic.svg",
        #[cfg(not(feature = "fire"))]
        "fire-symbolic.svg",
        #[cfg(not(feature = "firmware-update"))]
        "firmware-update-symbolic.svg",
        #[cfg(not(feature = "first-large"))]
        "first-large-symbolic.svg",
        #[cfg(not(feature = "first"))]
        "first-symbolic.svg",
        #[cfg(not(feature = "fish"))]
        "fish-symbolic.svg",
        #[cfg(not(feature = "flag-filled"))]
        "flag-filled-symbolic.svg",
        #[cfg(not(feature = "flag-outline-thick"))]
        "flag-outline-thick-symbolic.svg",
        #[cfg(not(feature = "flag-outline-thin"))]
        "flag-outline-thin-symbolic.svg",
        #[cfg(not(feature = "flap"))]
        "flap-symbolic.svg",
        #[cfg(not(feature = "flashlight-none"))]
        "flashlight-none-symbolic.svg",
        #[cfg(not(feature = "flashlight"))]
        "flashlight-symbolic.svg",
        #[cfg(not(feature = "flash-memory"))]
        "flash-memory-symbolic.svg",
        #[cfg(not(feature = "flatpak"))]
        "flatpak-symbolic.svg",
        #[cfg(not(feature = "floppy"))]
        "floppy-symbolic.svg",
        #[cfg(not(feature = "flying2"))]
        "flying2-symbolic.svg",
        #[cfg(not(feature = "flying"))]
        "flying-symbolic.svg",
        #[cfg(not(feature = "fog"))]
        "fog-symbolic.svg",
        #[cfg(not(feature = "folder-remote"))]
        "folder-remote-symbolic.svg",
        #[cfg(not(feature = "font-x-generic"))]
        "font-x-generic-symbolic.svg",
        #[cfg(not(feature = "football-american"))]
        "football-american-symbolic.svg",
        #[cfg(not(feature = "fuel"))]
        "fuel-symbolic.svg",
        #[cfg(not(feature = "function-exponential"))]
        "function-exponential-symbolic.svg",
        #[cfg(not(feature = "function-linear"))]
        "function-linear-symbolic.svg",
        #[cfg(not(feature = "function-parable-horizontal"))]
        "function-parable-horizontal-symbolic.svg",
        #[cfg(not(feature = "function-parable"))]
        "function-parable-symbolic.svg",
        #[cfg(not(feature = "function-third-order-horizontal"))]
        "function-third-order-horizontal-symbolic.svg",
        #[cfg(not(feature = "function-third-order"))]
        "function-third-order-symbolic.svg",
        #[cfg(not(feature = "funnel-outline"))]
        "funnel-outline-symbolic.svg",
        #[cfg(not(feature = "funnel"))]
        "funnel-symbolic.svg",
        #[cfg(not(feature = "gamepad2"))]
        "gamepad2-symbolic.svg",
        #[cfg(not(feature = "gamepad"))]
        "gamepad-symbolic.svg",
        #[cfg(not(feature = "garlic"))]
        "garlic-symbolic.svg",
        #[cfg(not(feature = "gear"))]
        "gear-symbolic.svg",
        #[cfg(not(feature = "general-properties"))]
        "general-properties-symbolic.svg",
        #[cfg(not(feature = "git-branch"))]
        "git-branch-symbolic.svg",
        #[cfg(not(feature = "git-merge"))]
        "git-merge-symbolic.svg",
        #[cfg(not(feature = "git"))]
        "git-symbolic.svg",
        #[cfg(not(feature = "globe-alt2"))]
        "globe-alt2-symbolic.svg",
        #[cfg(not(feature = "globe-alt"))]
        "globe-alt-symbolic.svg",
        #[cfg(not(feature = "globe"))]
        "globe-symbolic.svg",
        #[cfg(not(feature = "golf"))]
        "golf-symbolic.svg",
        #[cfg(not(feature = "graph2"))]
        "graph2-symbolic.svg",
        #[cfg(not(feature = "graph"))]
        "graph-symbolic.svg",
        #[cfg(not(feature = "graveyard"))]
        "graveyard-symbolic.svg",
        #[cfg(not(feature = "grid-filled"))]
        "grid-filled-symbolic.svg",
        #[cfg(not(feature = "grid-large"))]
        "grid-large-symbolic.svg",
        #[cfg(not(feature = "grid"))]
        "grid-symbolic.svg",
        #[cfg(not(feature = "group"))]
        "group-symbolic.svg",
        #[cfg(not(feature = "hand-fist-none"))]
        "hand-fist-none-symbolic.svg",
        #[cfg(not(feature = "hand-fist"))]
        "hand-fist-symbolic.svg",
        #[cfg(not(feature = "hand-middle-finger"))]
        "hand-middle-finger-symbolic.svg",
        #[cfg(not(feature = "hand-open"))]
        "hand-open-symbolic.svg",
        #[cfg(not(feature = "hand-point-horizontal"))]
        "hand-point-horizontal-symbolic.svg",
        #[cfg(not(feature = "hand-point-left"))]
        "hand-point-left-symbolic.svg",
        #[cfg(not(feature = "hand-point-right"))]
        "hand-point-right-symbolic.svg",
        #[cfg(not(feature = "hand-point"))]
        "hand-point-symbolic.svg",
        #[cfg(not(feature = "handshake"))]
        "handshake-symbolic.svg",
        #[cfg(not(feature = "hand-touch"))]
        "hand-touch-symbolic.svg",
        #[cfg(not(feature = "harddisk-inverted"))]
        "harddisk-inverted-symbolic.svg",
        #[cfg(not(feature = "harddisk"))]
        "harddisk-symbolic.svg",
        #[cfg(not(feature = "headphones"))]
        "headphones-symbolic.svg",
        #[cfg(not(feature = "headset"))]
        "headset-symbolic.svg",
        #[cfg(not(feature = "heal"))]
        "heal-symbolic.svg",
        #[cfg(not(feature = "heart-broken"))]
        "heart-broken-symbolic.svg",
        #[cfg(not(feature = "heart-filled"))]
        "heart-filled-symbolic.svg",
        #[cfg(not(feature = "heart-outline-thick"))]
        "heart-outline-thick-symbolic.svg",
        #[cfg(not(feature = "heart-outline-thin"))]
        "heart-outline-thin-symbolic.svg",
        #[cfg(not(feature = "hig"))]
        "hig-symbolic.svg",
        #[cfg(not(feature = "history-undo"))]
        "history-undo-symbolic.svg",
        #[cfg(not(feature = "hockey"))]
        "hockey-symbolic.svg",
        #[cfg(not(feature = "horizontal-arrows-disabled"))]
        "horizontal-arrows-disabled-symbolic.svg",
        #[cfg(not(feature = "horizontal-arrows-left"))]
        "horizontal-arrows-left-symbolic.svg",
        #[cfg(not(feature = "horizontal-arrows-none"))]
        "horizontal-arrows-none-symbolic.svg",
        #[cfg(not(feature = "horizontal-arrows-one-way"))]
        "horizontal-arrows-one-way-symbolic.svg",
        #[cfg(not(feature = "horizontal-arrows-right"))]
        "horizontal-arrows-right-symbolic.svg",
        #[cfg(not(feature = "horizontal-arrows"))]
        "horizontal-arrows-symbolic.svg",
        #[cfg(not(feature = "hospital-sign"))]
        "hospital-sign-symbolic.svg",
        #[cfg(not(feature = "hospital"))]
        "hospital-symbolic.svg",
        #[cfg(not(feature = "hourglass"))]
        "hourglass-symbolic.svg",
        #[cfg(not(feature = "h"))]
        "h-symbolic.svg",
        #[cfg(not(feature = "image-adjust-brightness"))]
        "image-adjust-brightness-symbolic.svg",
        #[cfg(not(feature = "image-adjust-contrast"))]
        "image-adjust-contrast-symbolic.svg",
        #[cfg(not(feature = "image-adjust-exposure"))]
        "image-adjust-exposure-symbolic.svg",
        #[cfg(not(feature = "image-adjust-highlights"))]
        "image-adjust-highlights-symbolic.svg",
        #[cfg(not(feature = "image-adjust-shadows"))]
        "image-adjust-shadows-symbolic.svg",
        #[cfg(not(feature = "image-alt"))]
        "image-alt-symbolic.svg",
        #[cfg(not(feature = "image-missing-round"))]
        "image-missing-round-symbolic.svg",
        #[cfg(not(feature = "image-missing"))]
        "image-missing-symbolic.svg",
        #[cfg(not(feature = "image-print"))]
        "image-print-symbolic.svg",
        #[cfg(not(feature = "image-round"))]
        "image-round-symbolic.svg",
        #[cfg(not(feature = "image"))]
        "image-symbolic.svg",
        #[cfg(not(feature = "inbox"))]
        "inbox-symbolic.svg",
        #[cfg(not(feature = "info"))]
        "info-symbolic.svg",
        #[cfg(not(feature = "ink-tool"))]
        "ink-tool-symbolic.svg",
        #[cfg(not(feature = "integral2"))]
        "integral2-symbolic.svg",
        #[cfg(not(feature = "integral3"))]
        "integral3-symbolic.svg",
        #[cfg(not(feature = "integral"))]
        "integral-symbolic.svg",
        #[cfg(not(feature = "inverse-fast-fourier-transform"))]
        "inverse-fast-fourier-transform-symbolic.svg",
        #[cfg(not(feature = "invert-colors"))]
        "invert-colors-symbolic.svg",
        #[cfg(not(feature = "iphone"))]
        "iphone-symbolic.svg",
        #[cfg(not(feature = "ipod"))]
        "ipod-symbolic.svg",
        #[cfg(not(feature = "issue"))]
        "issue-symbolic.svg",
        #[cfg(not(feature = "item-missing"))]
        "item-missing-symbolic.svg",
        #[cfg(not(feature = "joined-displays"))]
        "joined-displays-symbolic.svg",
        #[cfg(not(feature = "junk-alt"))]
        "junk-alt-symbolic.svg",
        #[cfg(not(feature = "junk"))]
        "junk-symbolic.svg",
        #[cfg(not(feature = "key2"))]
        "key2-symbolic.svg",
        #[cfg(not(feature = "keyboard2"))]
        "keyboard2-symbolic.svg",
        #[cfg(not(feature = "keyboard3"))]
        "keyboard3-symbolic.svg",
        #[cfg(not(feature = "keyboard-caps-lock-filled"))]
        "keyboard-caps-lock-filled-symbolic.svg",
        #[cfg(not(feature = "keyboard-caps-lock"))]
        "keyboard-caps-lock-symbolic.svg",
        #[cfg(not(feature = "keyboard-caps-lock-wide-filled"))]
        "keyboard-caps-lock-wide-filled-symbolic.svg",
        #[cfg(not(feature = "keyboard-caps-lock-wide"))]
        "keyboard-caps-lock-wide-symbolic.svg",
        #[cfg(not(feature = "keyboard-enter"))]
        "keyboard-enter-symbolic.svg",
        #[cfg(not(feature = "keyboard-extend"))]
        "keyboard-extend-symbolic.svg",
        #[cfg(not(feature = "keyboard-hide"))]
        "keyboard-hide-symbolic.svg",
        #[cfg(not(feature = "keyboard-layout-filled"))]
        "keyboard-layout-filled-symbolic.svg",
        #[cfg(not(feature = "keyboard-layout"))]
        "keyboard-layout-symbolic.svg",
        #[cfg(not(feature = "keyboard-option"))]
        "keyboard-option-symbolic.svg",
        #[cfg(not(feature = "keyboard-retract"))]
        "keyboard-retract-symbolic.svg",
        #[cfg(not(feature = "keyboard-shift-filled"))]
        "keyboard-shift-filled-symbolic.svg",
        #[cfg(not(feature = "keyboard-shift"))]
        "keyboard-shift-symbolic.svg",
        #[cfg(not(feature = "keyboard-shortcuts"))]
        "keyboard-shortcuts-symbolic.svg",
        #[cfg(not(feature = "keyboard"))]
        "keyboard-symbolic.svg",
        #[cfg(not(feature = "key"))]
        "key-symbolic.svg",
        #[cfg(not(feature = "language"))]
        "language-symbolic.svg",
        #[cfg(not(feature = "lan"))]
        "lan-symbolic.svg",
        #[cfg(not(feature = "large-brush"))]
        "large-brush-symbolic.svg",
        #[cfg(not(feature = "larger-brush"))]
        "larger-brush-symbolic.svg",
        #[cfg(not(feature = "last-large"))]
        "last-large-symbolic.svg",
        #[cfg(not(feature = "last"))]
        "last-symbolic.svg",
        #[cfg(not(feature = "leaflet"))]
        "leaflet-symbolic.svg",
        #[cfg(not(feature = "left-large"))]
        "left-large-symbolic.svg",
        #[cfg(not(feature = "left"))]
        "left-symbolic.svg",
        #[cfg(not(feature = "library-artists"))]
        "library-artists-symbolic.svg",
        #[cfg(not(feature = "library-music"))]
        "library-music-symbolic.svg",
        #[cfg(not(feature = "library"))]
        "library-symbolic.svg",
        #[cfg(not(feature = "lightbulb"))]
        "lightbulb-symbolic.svg",
        #[cfg(not(feature = "list-compact"))]
        "list-compact-symbolic.svg",
        #[cfg(not(feature = "list-large"))]
        "list-large-symbolic.svg",
        #[cfg(not(feature = "list"))]
        "list-symbolic.svg",
        #[cfg(not(feature = "loaf"))]
        "loaf-symbolic.svg",
        #[cfg(not(feature = "lock-small-open"))]
        "lock-small-open-symbolic.svg",
        #[cfg(not(feature = "lock-small"))]
        "lock-small-symbolic.svg",
        #[cfg(not(feature = "loupe-large"))]
        "loupe-large-symbolic.svg",
        #[cfg(not(feature = "loupe"))]
        "loupe-symbolic.svg",
        #[cfg(not(feature = "loupe-with-arrow"))]
        "loupe-with-arrow-symbolic.svg",
        #[cfg(not(feature = "loupe-with-heart"))]
        "loupe-with-heart-symbolic.svg",
        #[cfg(not(feature = "low-vision"))]
        "low-vision-symbolic.svg",
        #[cfg(not(feature = "magic-wand"))]
        "magic-wand-symbolic.svg",
        #[cfg(not(feature = "mail-archive"))]
        "mail-archive-symbolic.svg",
        #[cfg(not(feature = "mailbox"))]
        "mailbox-symbolic.svg",
        #[cfg(not(feature = "mail-read"))]
        "mail-read-symbolic.svg",
        #[cfg(not(feature = "mail-secure"))]
        "mail-secure-symbolic.svg",
        #[cfg(not(feature = "mail"))]
        "mail-symbolic.svg",
        #[cfg(not(feature = "map-marker-2"))]
        "map-marker-2-symbolic.svg",
        #[cfg(not(feature = "map-marker"))]
        "map-marker-symbolic.svg",
        #[cfg(not(feature = "map"))]
        "map-symbolic.svg",
        #[cfg(not(feature = "mark2"))]
        "mark2-symbolic.svg",
        #[cfg(not(feature = "markdown"))]
        "markdown-symbolic.svg",
        #[cfg(not(feature = "marker"))]
        "marker-symbolic.svg",
        #[cfg(not(feature = "mark"))]
        "mark-symbolic.svg",
        #[cfg(not(feature = "meat"))]
        "meat-symbolic.svg",
        #[cfg(not(feature = "meeting"))]
        "meeting-symbolic.svg",
        #[cfg(not(feature = "menu-large"))]
        "menu-large-symbolic.svg",
        #[cfg(not(feature = "menu"))]
        "menu-symbolic.svg",
        #[cfg(not(feature = "merge"))]
        "merge-symbolic.svg",
        #[cfg(not(feature = "microphone2"))]
        "microphone2-symbolic.svg",
        #[cfg(not(feature = "microphone"))]
        "microphone-symbolic.svg",
        #[cfg(not(feature = "minus-large"))]
        "minus-large-symbolic.svg",
        #[cfg(not(feature = "minus"))]
        "minus-symbolic.svg",
        #[cfg(not(feature = "mobile-network"))]
        "mobile-network-symbolic.svg",
        #[cfg(not(feature = "modem"))]
        "modem-symbolic.svg",
        #[cfg(not(feature = "money-clip"))]
        "money-clip-symbolic.svg",
        #[cfg(not(feature = "money-none"))]
        "money-none-symbolic.svg",
        #[cfg(not(feature = "money"))]
        "money-symbolic.svg",
        #[cfg(not(feature = "monitor-pick"))]
        "monitor-pick-symbolic.svg",
        #[cfg(not(feature = "month"))]
        "month-symbolic.svg",
        #[cfg(not(feature = "moon-alt2"))]
        "moon-alt2-symbolic.svg",
        #[cfg(not(feature = "moon-alt"))]
        "moon-alt-symbolic.svg",
        #[cfg(not(feature = "moon-clouds-outline"))]
        "moon-clouds-outline-symbolic.svg",
        #[cfg(not(feature = "moon-filled"))]
        "moon-filled-symbolic.svg",
        #[cfg(not(feature = "moon-outline"))]
        "moon-outline-symbolic.svg",
        #[cfg(not(feature = "moon"))]
        "moon-symbolic.svg",
        #[cfg(not(feature = "mountain"))]
        "mountain-symbolic.svg",
        #[cfg(not(feature = "mouse"))]
        "mouse-symbolic.svg",
        #[cfg(not(feature = "mouse-wireless-disabled-filled"))]
        "mouse-wireless-disabled-filled-symbolic.svg",
        #[cfg(not(feature = "mouse-wireless-disabled"))]
        "mouse-wireless-disabled-symbolic.svg",
        #[cfg(not(feature = "mouse-wireless-filled"))]
        "mouse-wireless-filled-symbolic.svg",
        #[cfg(not(feature = "mouse-wireless"))]
        "mouse-wireless-symbolic.svg",
        #[cfg(not(feature = "mouse-with-smaller-scrollwheel"))]
        "mouse-with-smaller-scrollwheel-symbolic.svg",
        #[cfg(not(feature = "move-tool"))]
        "move-tool-symbolic.svg",
        #[cfg(not(feature = "move-to-window"))]
        "move-to-window-symbolic.svg",
        #[cfg(not(feature = "multitasking"))]
        "multitasking-symbolic.svg",
        #[cfg(not(feature = "multitasking-windows"))]
        "multitasking-windows-symbolic.svg",
        #[cfg(not(feature = "museum"))]
        "museum-symbolic.svg",
        #[cfg(not(feature = "music-artist2"))]
        "music-artist2-symbolic.svg",
        #[cfg(not(feature = "music-artist"))]
        "music-artist-symbolic.svg",
        #[cfg(not(feature = "music-note-single"))]
        "music-note-single-symbolic.svg",
        #[cfg(not(feature = "music-note"))]
        "music-note-symbolic.svg",
        #[cfg(not(feature = "music-queue"))]
        "music-queue-symbolic.svg",
        #[cfg(not(feature = "navigate"))]
        "navigate-symbolic.svg",
        #[cfg(not(feature = "network-cellular-no-data-signal-excellent"))]
        "network-cellular-no-data-signal-excellent-symbolic.svg",
        #[cfg(not(feature = "network-cellular-no-data-signal-good"))]
        "network-cellular-no-data-signal-good-symbolic.svg",
        #[cfg(not(feature = "network-cellular-no-data-signal-none"))]
        "network-cellular-no-data-signal-none-symbolic.svg",
        #[cfg(not(feature = "network-cellular-no-data-signal-ok"))]
        "network-cellular-no-data-signal-ok-symbolic.svg",
        #[cfg(not(feature = "network-cellular-no-data-signal-weak"))]
        "network-cellular-no-data-signal-weak-symbolic.svg",
        #[cfg(not(feature = "network-printer"))]
        "network-printer-symbolic.svg",
        #[cfg(not(feature = "network-raid"))]
        "network-raid-symbolic.svg",
        #[cfg(not(feature = "network-server"))]
        "network-server-symbolic.svg",
        #[cfg(not(feature = "network-workgroup"))]
        "network-workgroup-symbolic.svg",
        #[cfg(not(feature = "newspaper-rounded"))]
        "newspaper-rounded-symbolic.svg",
        #[cfg(not(feature = "newspaper"))]
        "newspaper-symbolic.svg",
        #[cfg(not(feature = "nintendo-controller"))]
        "nintendo-controller-symbolic.svg",
        #[cfg(not(feature = "no-bed"))]
        "no-bed-symbolic.svg",
        #[cfg(not(feature = "no-bluetooth"))]
        "no-bluetooth-symbolic.svg",
        #[cfg(not(feature = "no-flying"))]
        "no-flying-symbolic.svg",
        #[cfg(not(feature = "noodles"))]
        "noodles-symbolic.svg",
        #[cfg(not(feature = "normalize"))]
        "normalize-symbolic.svg",
        #[cfg(not(feature = "note2"))]
        "note2-symbolic.svg",
        #[cfg(not(feature = "notepad"))]
        "notepad-symbolic.svg",
        #[cfg(not(feature = "note"))]
        "note-symbolic.svg",
        #[cfg(not(feature = "not-junk-alt"))]
        "not-junk-alt-symbolic.svg",
        #[cfg(not(feature = "not-junk"))]
        "not-junk-symbolic.svg",
        #[cfg(not(feature = "no-toilets"))]
        "no-toilets-symbolic.svg",
        #[cfg(not(feature = "no-wheelchair"))]
        "no-wheelchair-symbolic.svg",
        #[cfg(not(feature = "nudity-none"))]
        "nudity-none-symbolic.svg",
        #[cfg(not(feature = "nudity"))]
        "nudity-symbolic.svg",
        #[cfg(not(feature = "nut"))]
        "nut-symbolic.svg",
        #[cfg(not(feature = "object-layout"))]
        "object-layout-symbolic.svg",
        #[cfg(not(feature = "object-packing"))]
        "object-packing-symbolic.svg",
        #[cfg(not(feature = "offline-globe"))]
        "offline-globe-symbolic.svg",
        #[cfg(not(feature = "online"))]
        "online-symbolic.svg",
        #[cfg(not(feature = "opacity"))]
        "opacity-symbolic.svg",
        #[cfg(not(feature = "open-book"))]
        "open-book-symbolic.svg",
        #[cfg(not(feature = "outbox"))]
        "outbox-symbolic.svg",
        #[cfg(not(feature = "overlapping-windows"))]
        "overlapping-windows-symbolic.svg",
        #[cfg(not(feature = "package"))]
        "package-symbolic.svg",
        #[cfg(not(feature = "package-x-generic"))]
        "package-x-generic-symbolic.svg",
        #[cfg(not(feature = "padlock2-open"))]
        "padlock2-open-symbolic.svg",
        #[cfg(not(feature = "padlock2"))]
        "padlock2-symbolic.svg",
        #[cfg(not(feature = "padlock-open"))]
        "padlock-open-symbolic.svg",
        #[cfg(not(feature = "padlock"))]
        "padlock-symbolic.svg",
        #[cfg(not(feature = "paintbrush"))]
        "paintbrush-symbolic.svg",
        #[cfg(not(feature = "panorama-360"))]
        "panorama-360-symbolic.svg",
        #[cfg(not(feature = "panorama-horizontal"))]
        "panorama-horizontal-symbolic.svg",
        #[cfg(not(feature = "panorama-vertical"))]
        "panorama-vertical-symbolic.svg",
        #[cfg(not(feature = "paper-filled"))]
        "paper-filled-symbolic.svg",
        #[cfg(not(feature = "paper-plane"))]
        "paper-plane-symbolic.svg",
        #[cfg(not(feature = "paper"))]
        "paper-symbolic.svg",
        #[cfg(not(feature = "papyrus"))]
        "papyrus-symbolic.svg",
        #[cfg(not(feature = "papyrus-vertical"))]
        "papyrus-vertical-symbolic.svg",
        #[cfg(not(feature = "parent"))]
        "parent-symbolic.svg",
        #[cfg(not(feature = "parking-sign"))]
        "parking-sign-symbolic.svg",
        #[cfg(not(feature = "password-entry"))]
        "password-entry-symbolic.svg",
        #[cfg(not(feature = "path-erase-delete"))]
        "path-erase-delete-symbolic.svg",
        #[cfg(not(feature = "path-erase-split2"))]
        "path-erase-split2-symbolic.svg",
        #[cfg(not(feature = "path-erase-split"))]
        "path-erase-split-symbolic.svg",
        #[cfg(not(feature = "path-tool"))]
        "path-tool-symbolic.svg",
        #[cfg(not(feature = "pause-large"))]
        "pause-large-symbolic.svg",
        #[cfg(not(feature = "pause"))]
        "pause-symbolic.svg",
        #[cfg(not(feature = "pci-card"))]
        "pci-card-symbolic.svg",
        #[cfg(not(feature = "pda"))]
        "pda-symbolic.svg",
        #[cfg(not(feature = "pencil-and-paper"))]
        "pencil-and-paper-symbolic.svg",
        #[cfg(not(feature = "pencil"))]
        "pencil-symbolic.svg",
        #[cfg(not(feature = "penguin-alt"))]
        "penguin-alt-symbolic.svg",
        #[cfg(not(feature = "penguin"))]
        "penguin-symbolic.svg",
        #[cfg(not(feature = "people"))]
        "people-symbolic.svg",
        #[cfg(not(feature = "pepper"))]
        "pepper-symbolic.svg",
        #[cfg(not(feature = "permissions-advertising"))]
        "permissions-advertising-symbolic.svg",
        #[cfg(not(feature = "permissions-camera"))]
        "permissions-camera-symbolic.svg",
        #[cfg(not(feature = "permissions-generic"))]
        "permissions-generic-symbolic.svg",
        #[cfg(not(feature = "permissions-location"))]
        "permissions-location-symbolic.svg",
        #[cfg(not(feature = "permissions-microphone"))]
        "permissions-microphone-symbolic.svg",
        #[cfg(not(feature = "permissions-notifications"))]
        "permissions-notifications-symbolic.svg",
        #[cfg(not(feature = "permissions-password"))]
        "permissions-password-symbolic.svg",
        #[cfg(not(feature = "person2"))]
        "person2-symbolic.svg",
        #[cfg(not(feature = "person"))]
        "person-symbolic.svg",
        #[cfg(not(feature = "phone-disabled"))]
        "phone-disabled-symbolic.svg",
        #[cfg(not(feature = "phonelink2-off"))]
        "phonelink2-off-symbolic.svg",
        #[cfg(not(feature = "phonelink2"))]
        "phonelink2-symbolic.svg",
        #[cfg(not(feature = "phonelink-delete"))]
        "phonelink-delete-symbolic.svg",
        #[cfg(not(feature = "phonelink-lock"))]
        "phonelink-lock-symbolic.svg",
        #[cfg(not(feature = "phonelink-off"))]
        "phonelink-off-symbolic.svg",
        #[cfg(not(feature = "phonelink-ring"))]
        "phonelink-ring-symbolic.svg",
        #[cfg(not(feature = "phonelink-setup"))]
        "phonelink-setup-symbolic.svg",
        #[cfg(not(feature = "phonelink"))]
        "phonelink-symbolic.svg",
        #[cfg(not(feature = "phone-oldschool"))]
        "phone-oldschool-symbolic.svg",
        #[cfg(not(feature = "phone"))]
        "phone-symbolic.svg",
        #[cfg(not(feature = "phone-vibrate"))]
        "phone-vibrate-symbolic.svg",
        #[cfg(not(feature = "phosh"))]
        "phosh-symbolic.svg",
        #[cfg(not(feature = "photo-camera"))]
        "photo-camera-symbolic.svg",
        #[cfg(not(feature = "pin-location"))]
        "pin-location-symbolic.svg",
        #[cfg(not(feature = "pin"))]
        "pin-symbolic.svg",
        #[cfg(not(feature = "pipette"))]
        "pipette-symbolic.svg",
        #[cfg(not(feature = "pip-in"))]
        "pip-in-symbolic.svg",
        #[cfg(not(feature = "pip-out"))]
        "pip-out-symbolic.svg",
        #[cfg(not(feature = "playback-error"))]
        "playback-error-symbolic.svg",
        #[cfg(not(feature = "playback-options"))]
        "playback-options-symbolic.svg",
        #[cfg(not(feature = "playback-speed"))]
        "playback-speed-symbolic.svg",
        #[cfg(not(feature = "playback"))]
        "playback-symbolic.svg",
        #[cfg(not(feature = "play-large-diabled"))]
        "play-large-diabled-symbolic.svg",
        #[cfg(not(feature = "play-large"))]
        "play-large-symbolic.svg",
        #[cfg(not(feature = "playlist2"))]
        "playlist2-symbolic.svg",
        #[cfg(not(feature = "playlist"))]
        "playlist-symbolic.svg",
        #[cfg(not(feature = "play"))]
        "play-symbolic.svg",
        #[cfg(not(feature = "plus-large"))]
        "plus-large-symbolic.svg",
        #[cfg(not(feature = "plus"))]
        "plus-symbolic.svg",
        #[cfg(not(feature = "podcast"))]
        "podcast-symbolic.svg",
        #[cfg(not(feature = "portal"))]
        "portal-symbolic.svg",
        #[cfg(not(feature = "positive-feedback"))]
        "positive-feedback-symbolic.svg",
        #[cfg(not(feature = "post-box"))]
        "post-box-symbolic.svg",
        #[cfg(not(feature = "power"))]
        "power-symbolic.svg",
        #[cfg(not(feature = "printer-network"))]
        "printer-network-symbolic.svg",
        #[cfg(not(feature = "printer-round"))]
        "printer-round-symbolic.svg",
        #[cfg(not(feature = "printer"))]
        "printer-symbolic.svg",
        #[cfg(not(feature = "profit"))]
        "profit-symbolic.svg",
        #[cfg(not(feature = "projector"))]
        "projector-symbolic.svg",
        #[cfg(not(feature = "pub"))]
        "pub-symbolic.svg",
        #[cfg(not(feature = "puzzle-piece"))]
        "puzzle-piece-symbolic.svg",
        #[cfg(not(feature = "qr-code-scanner"))]
        "qr-code-scanner-symbolic.svg",
        #[cfg(not(feature = "qr-code"))]
        "qr-code-symbolic.svg",
        #[cfg(not(feature = "question-round"))]
        "question-round-symbolic.svg",
        #[cfg(not(feature = "question"))]
        "question-symbolic.svg",
        #[cfg(not(feature = "quotation"))]
        "quotation-symbolic.svg",
        #[cfg(not(feature = "raid"))]
        "raid-symbolic.svg",
        #[cfg(not(feature = "rain-alt"))]
        "rain-alt-symbolic.svg",
        #[cfg(not(feature = "rain-outline"))]
        "rain-outline-symbolic.svg",
        #[cfg(not(feature = "rain-scattered-outline"))]
        "rain-scattered-outline-symbolic.svg",
        #[cfg(not(feature = "rain"))]
        "rain-symbolic.svg",
        #[cfg(not(feature = "record-screen"))]
        "record-screen-symbolic.svg",
        #[cfg(not(feature = "refresh-large"))]
        "refresh-large-symbolic.svg",
        #[cfg(not(feature = "refresh"))]
        "refresh-symbolic.svg",
        #[cfg(not(feature = "regex"))]
        "regex-symbolic.svg",
        #[cfg(not(feature = "remote-terminal"))]
        "remote-terminal-symbolic.svg",
        #[cfg(not(feature = "resize-mode"))]
        "resize-mode-symbolic.svg",
        #[cfg(not(feature = "resources"))]
        "resources-symbolic.svg",
        #[cfg(not(feature = "restaurant"))]
        "restaurant-symbolic.svg",
        #[cfg(not(feature = "rich-text"))]
        "rich-text-symbolic.svg",
        #[cfg(not(feature = "right-large"))]
        "right-large-symbolic.svg",
        #[cfg(not(feature = "right"))]
        "right-symbolic.svg",
        #[cfg(not(feature = "roll"))]
        "roll-symbolic.svg",
        #[cfg(not(feature = "roll-vertical"))]
        "roll-vertical-symbolic.svg",
        #[cfg(not(feature = "rotate"))]
        "rotate-symbolic.svg",
        #[cfg(not(feature = "rotation-lock-disabled"))]
        "rotation-lock-disabled-symbolic.svg",
        #[cfg(not(feature = "rotation-lock"))]
        "rotation-lock-symbolic.svg",
        #[cfg(not(feature = "routing"))]
        "routing-symbolic.svg",
        #[cfg(not(feature = "salami"))]
        "salami-symbolic.svg",
        #[cfg(not(feature = "scales-detail"))]
        "scales-detail-symbolic.svg",
        #[cfg(not(feature = "scales"))]
        "scales-symbolic.svg",
        #[cfg(not(feature = "scale"))]
        "scale-symbolic.svg",
        #[cfg(not(feature = "scanner"))]
        "scanner-symbolic.svg",
        #[cfg(not(feature = "scattered-clouds"))]
        "scattered-clouds-symbolic.svg",
        #[cfg(not(feature = "school"))]
        "school-symbolic.svg",
        #[cfg(not(feature = "scissors"))]
        "scissors-symbolic.svg",
        #[cfg(not(feature = "screencast-recorded"))]
        "screencast-recorded-symbolic.svg",
        #[cfg(not(feature = "screen-privacy2"))]
        "screen-privacy2-symbolic.svg",
        #[cfg(not(feature = "screen-privacy3"))]
        "screen-privacy3-symbolic.svg",
        #[cfg(not(feature = "screen-privacy4"))]
        "screen-privacy4-symbolic.svg",
        #[cfg(not(feature = "screen-privacy5"))]
        "screen-privacy5-symbolic.svg",
        #[cfg(not(feature = "screen-privacy6"))]
        "screen-privacy6-symbolic.svg",
        #[cfg(not(feature = "screen-privacy7-disabled"))]
        "screen-privacy7-disabled-symbolic.svg",
        #[cfg(not(feature = "screen-privacy7"))]
        "screen-privacy7-symbolic.svg",
        #[cfg(not(feature = "screen-privacy-disabled7"))]
        "screen-privacy-disabled7-symbolic.svg",
        #[cfg(not(feature = "screen-privacy-disabled"))]
        "screen-privacy-disabled-symbolic.svg",
        #[cfg(not(feature = "screen-privacy"))]
        "screen-privacy-symbolic.svg",
        #[cfg(not(feature = "screenshooter"))]
        "screenshooter-symbolic.svg",
        #[cfg(not(feature = "screenshot-recorded"))]
        "screenshot-recorded-symbolic.svg",
        #[cfg(not(feature = "screenshot"))]
        "screenshot-symbolic.svg",
        #[cfg(not(feature = "scroll-on-a-roll"))]
        "scroll-on-a-roll-symbolic.svg",
        #[cfg(not(feature = "scroll"))]
        "scroll-symbolic.svg",
        #[cfg(not(feature = "selection-opaque-2"))]
        "selection-opaque-2-symbolic.svg",
        #[cfg(not(feature = "selection-opaque-3"))]
        "selection-opaque-3-symbolic.svg",
        #[cfg(not(feature = "selection-opaque"))]
        "selection-opaque-symbolic.svg",
        #[cfg(not(feature = "selection"))]
        "selection-symbolic.svg",
        #[cfg(not(feature = "select-mode"))]
        "select-mode-symbolic.svg",
        #[cfg(not(feature = "select"))]
        "select-symbolic.svg",
        #[cfg(not(feature = "send-alt"))]
        "send-alt-symbolic.svg",
        #[cfg(not(feature = "send"))]
        "send-symbolic.svg",
        #[cfg(not(feature = "sentiment-dissatisfied"))]
        "sentiment-dissatisfied-symbolic.svg",
        #[cfg(not(feature = "sentiment-neutral"))]
        "sentiment-neutral-symbolic.svg",
        #[cfg(not(feature = "sentiment-satisfied"))]
        "sentiment-satisfied-symbolic.svg",
        #[cfg(not(feature = "sentiment-very-dissatisfied"))]
        "sentiment-very-dissatisfied-symbolic.svg",
        #[cfg(not(feature = "sentiment-very-satisfied"))]
        "sentiment-very-satisfied-symbolic.svg",
        #[cfg(not(feature = "server-pick"))]
        "server-pick-symbolic.svg",
        #[cfg(not(feature = "settings"))]
        "settings-symbolic.svg",
        #[cfg(not(feature = "shapes-large"))]
        "shapes-large-symbolic.svg",
        #[cfg(not(feature = "shapes"))]
        "shapes-symbolic.svg",
        #[cfg(not(feature = "share-alt"))]
        "share-alt-symbolic.svg",
        #[cfg(not(feature = "share"))]
        "share-symbolic.svg",
        #[cfg(not(feature = "shear"))]
        "shear-symbolic.svg",
        #[cfg(not(feature = "shell-overview"))]
        "shell-overview-symbolic.svg",
        #[cfg(not(feature = "shell"))]
        "shell-symbolic.svg",
        #[cfg(not(feature = "shield-danger"))]
        "shield-danger-symbolic.svg",
        #[cfg(not(feature = "shield-safe"))]
        "shield-safe-symbolic.svg",
        #[cfg(not(feature = "shield-warning"))]
        "shield-warning-symbolic.svg",
        #[cfg(not(feature = "shift"))]
        "shift-symbolic.svg",
        #[cfg(not(feature = "shoe-box"))]
        "shoe-box-symbolic.svg",
        #[cfg(not(feature = "shopping-cart"))]
        "shopping-cart-symbolic.svg",
        #[cfg(not(feature = "showers"))]
        "showers-symbolic.svg",
        #[cfg(not(feature = "sidebar-toggle-left"))]
        "sidebar-toggle-left-symbolic.svg",
        #[cfg(not(feature = "sidebar-toggle-right"))]
        "sidebar-toggle-right-symbolic.svg",
        #[cfg(not(feature = "signature-bad"))]
        "signature-bad-symbolic.svg",
        #[cfg(not(feature = "signature"))]
        "signature-symbolic.svg",
        #[cfg(not(feature = "sign-language"))]
        "sign-language-symbolic.svg",
        #[cfg(not(feature = "sim"))]
        "sim-symbolic.svg",
        #[cfg(not(feature = "single-display"))]
        "single-display-symbolic.svg",
        #[cfg(not(feature = "size-horizontally"))]
        "size-horizontally-symbolic.svg",
        #[cfg(not(feature = "size-left"))]
        "size-left-symbolic.svg",
        #[cfg(not(feature = "size-right"))]
        "size-right-symbolic.svg",
        #[cfg(not(feature = "size-vertically"))]
        "size-vertically-symbolic.svg",
        #[cfg(not(feature = "skip-backwards-10"))]
        "skip-backwards-10-symbolic.svg",
        #[cfg(not(feature = "skip-backwards-30"))]
        "skip-backwards-30-symbolic.svg",
        #[cfg(not(feature = "skip-forward-10"))]
        "skip-forward-10-symbolic.svg",
        #[cfg(not(feature = "skip-forward-30"))]
        "skip-forward-30-symbolic.svg",
        #[cfg(not(feature = "skull-small"))]
        "skull-small-symbolic.svg",
        #[cfg(not(feature = "skull"))]
        "skull-symbolic.svg",
        #[cfg(not(feature = "small-x"))]
        "small-x-symbolic.svg",
        #[cfg(not(feature = "smartcard"))]
        "smartcard-symbolic.svg",
        #[cfg(not(feature = "smartphone"))]
        "smartphone-symbolic.svg",
        #[cfg(not(feature = "smile"))]
        "smile-symbolic.svg",
        #[cfg(not(feature = "smoothen"))]
        "smoothen-symbolic.svg",
        #[cfg(not(feature = "smudge-finger"))]
        "smudge-finger-symbolic.svg",
        #[cfg(not(feature = "snapshots-alt"))]
        "snapshots-alt-symbolic.svg",
        #[cfg(not(feature = "snapshots"))]
        "snapshots-symbolic.svg",
        #[cfg(not(feature = "snap"))]
        "snap-symbolic.svg",
        #[cfg(not(feature = "snow-outline"))]
        "snow-outline-symbolic.svg",
        #[cfg(not(feature = "snow"))]
        "snow-symbolic.svg",
        #[cfg(not(feature = "social-network-none"))]
        "social-network-none-symbolic.svg",
        #[cfg(not(feature = "social-network"))]
        "social-network-symbolic.svg",
        #[cfg(not(feature = "sonar"))]
        "sonar-symbolic.svg",
        #[cfg(not(feature = "soundcard"))]
        "soundcard-symbolic.svg",
        #[cfg(not(feature = "sound-wave-alt"))]
        "sound-wave-alt-symbolic.svg",
        #[cfg(not(feature = "sound-wave"))]
        "sound-wave-symbolic.svg",
        #[cfg(not(feature = "soup"))]
        "soup-symbolic.svg",
        #[cfg(not(feature = "source-pick"))]
        "source-pick-symbolic.svg",
        #[cfg(not(feature = "speakers"))]
        "speakers-symbolic.svg",
        #[cfg(not(feature = "speedometer2"))]
        "speedometer2-symbolic.svg",
        #[cfg(not(feature = "speedometer3"))]
        "speedometer3-symbolic.svg",
        #[cfg(not(feature = "speedometer4"))]
        "speedometer4-symbolic.svg",
        #[cfg(not(feature = "speedometer"))]
        "speedometer-symbolic.svg",
        #[cfg(not(feature = "spinner"))]
        "spinner-symbolic.svg",
        #[cfg(not(feature = "spring"))]
        "spring-symbolic.svg",
        #[cfg(not(feature = "square-filled"))]
        "square-filled-symbolic.svg",
        #[cfg(not(feature = "square-outline-thick"))]
        "square-outline-thick-symbolic.svg",
        #[cfg(not(feature = "square-outline-thin"))]
        "square-outline-thin-symbolic.svg",
        #[cfg(not(feature = "ssd"))]
        "ssd-symbolic.svg",
        #[cfg(not(feature = "stacked-plates"))]
        "stacked-plates-symbolic.svg",
        #[cfg(not(feature = "stamp"))]
        "stamp-symbolic.svg",
        #[cfg(not(feature = "star-filled-rounded"))]
        "star-filled-rounded-symbolic.svg",
        #[cfg(not(feature = "star-filled"))]
        "star-filled-symbolic.svg",
        #[cfg(not(feature = "star-large"))]
        "star-large-symbolic.svg",
        #[cfg(not(feature = "star-outline-half-left"))]
        "star-outline-half-left-symbolic.svg",
        #[cfg(not(feature = "star-outline-half-right"))]
        "star-outline-half-right-symbolic.svg",
        #[cfg(not(feature = "star-outline-rounded"))]
        "star-outline-rounded-symbolic.svg",
        #[cfg(not(feature = "star-outline-thick"))]
        "star-outline-thick-symbolic.svg",
        #[cfg(not(feature = "star-outline-thin"))]
        "star-outline-thin-symbolic.svg",
        #[cfg(not(feature = "step-back"))]
        "step-back-symbolic.svg",
        #[cfg(not(feature = "step-in"))]
        "step-in-symbolic.svg",
        #[cfg(not(feature = "step-out"))]
        "step-out-symbolic.svg",
        #[cfg(not(feature = "step-over"))]
        "step-over-symbolic.svg",
        #[cfg(not(feature = "steps"))]
        "steps-symbolic.svg",
        #[cfg(not(feature = "stop-large"))]
        "stop-large-symbolic.svg",
        #[cfg(not(feature = "stop-sign-large"))]
        "stop-sign-large-symbolic.svg",
        #[cfg(not(feature = "stop-sign"))]
        "stop-sign-symbolic.svg",
        #[cfg(not(feature = "stop"))]
        "stop-symbolic.svg",
        #[cfg(not(feature = "stopwatch"))]
        "stopwatch-symbolic.svg",
        #[cfg(not(feature = "storm-outline"))]
        "storm-outline-symbolic.svg",
        #[cfg(not(feature = "storm"))]
        "storm-symbolic.svg",
        #[cfg(not(feature = "strong-language-none"))]
        "strong-language-none-symbolic.svg",
        #[cfg(not(feature = "strong-language"))]
        "strong-language-symbolic.svg",
        #[cfg(not(feature = "subtitles"))]
        "subtitles-symbolic.svg",
        #[cfg(not(feature = "success"))]
        "success-symbolic.svg",
        #[cfg(not(feature = "sun-alt"))]
        "sun-alt-symbolic.svg",
        #[cfg(not(feature = "sun-outline"))]
        "sun-outline-symbolic.svg",
        #[cfg(not(feature = "sun"))]
        "sun-symbolic.svg",
        #[cfg(not(feature = "table"))]
        "table-symbolic.svg",
        #[cfg(not(feature = "tablet"))]
        "tablet-symbolic.svg",
        #[cfg(not(feature = "tab-new-filled"))]
        "tab-new-filled-symbolic.svg",
        #[cfg(not(feature = "tab-new-large"))]
        "tab-new-large-symbolic.svg",
        #[cfg(not(feature = "tab-new"))]
        "tab-new-symbolic.svg",
        #[cfg(not(feature = "tabs-stack"))]
        "tabs-stack-symbolic.svg",
        #[cfg(not(feature = "tab"))]
        "tab-symbolic.svg",
        #[cfg(not(feature = "tag"))]
        "tag-symbolic.svg",
        #[cfg(not(feature = "tape"))]
        "tape-symbolic.svg",
        #[cfg(not(feature = "task-assigned"))]
        "task-assigned-symbolic.svg",
        #[cfg(not(feature = "task-assigned-to"))]
        "task-assigned-to-symbolic.svg",
        #[cfg(not(feature = "task-recurring"))]
        "task-recurring-symbolic.svg",
        #[cfg(not(feature = "task"))]
        "task-symbolic.svg",
        #[cfg(not(feature = "tea"))]
        "tea-symbolic.svg",
        #[cfg(not(feature = "tennis"))]
        "tennis-symbolic.svg",
        #[cfg(not(feature = "terminal"))]
        "terminal-symbolic.svg",
        #[cfg(not(feature = "test-pass"))]
        "test-pass-symbolic.svg",
        #[cfg(not(feature = "test"))]
        "test-symbolic.svg",
        #[cfg(not(feature = "text2"))]
        "text2-symbolic.svg",
        #[cfg(not(feature = "text3"))]
        "text3-symbolic.svg",
        #[cfg(not(feature = "text-bold"))]
        "text-bold-symbolic.svg",
        #[cfg(not(feature = "text-direction-ltr"))]
        "text-direction-ltr-symbolic.svg",
        #[cfg(not(feature = "text-direction-rtl"))]
        "text-direction-rtl-symbolic.svg",
        #[cfg(not(feature = "text-indent-less"))]
        "text-indent-less-symbolic.svg",
        #[cfg(not(feature = "text-indent-more"))]
        "text-indent-more-symbolic.svg",
        #[cfg(not(feature = "text-italic"))]
        "text-italic-symbolic.svg",
        #[cfg(not(feature = "text-justify-center"))]
        "text-justify-center-symbolic.svg",
        #[cfg(not(feature = "text-justify-fill"))]
        "text-justify-fill-symbolic.svg",
        #[cfg(not(feature = "text-justify-left"))]
        "text-justify-left-symbolic.svg",
        #[cfg(not(feature = "text-justify-right"))]
        "text-justify-right-symbolic.svg",
        #[cfg(not(feature = "text-squiggly"))]
        "text-squiggly-symbolic.svg",
        #[cfg(not(feature = "text-strikethrough"))]
        "text-strikethrough-symbolic.svg",
        #[cfg(not(feature = "text"))]
        "text-symbolic.svg",
        #[cfg(not(feature = "text-underline"))]
        "text-underline-symbolic.svg",
        #[cfg(not(feature = "theater"))]
        "theater-symbolic.svg",
        #[cfg(not(feature = "thumbs-down"))]
        "thumbs-down-symbolic.svg",
        #[cfg(not(feature = "thumbs-up"))]
        "thumbs-up-symbolic.svg",
        #[cfg(not(feature = "thunderbolt"))]
        "thunderbolt-symbolic.svg",
        #[cfg(not(feature = "ticket-special"))]
        "ticket-special-symbolic.svg",
        #[cfg(not(feature = "ticket"))]
        "ticket-symbolic.svg",
        #[cfg(not(feature = "timer-sand"))]
        "timer-sand-symbolic.svg",
        #[cfg(not(feature = "timer"))]
        "timer-symbolic.svg",
        #[cfg(not(feature = "today-alt"))]
        "today-alt-symbolic.svg",
        #[cfg(not(feature = "today"))]
        "today-symbolic.svg",
        #[cfg(not(feature = "toilets"))]
        "toilets-symbolic.svg",
        #[cfg(not(feature = "toolbars"))]
        "toolbars-symbolic.svg",
        #[cfg(not(feature = "top-large"))]
        "top-large-symbolic.svg",
        #[cfg(not(feature = "top"))]
        "top-symbolic.svg",
        #[cfg(not(feature = "tornado"))]
        "tornado-symbolic.svg",
        #[cfg(not(feature = "touchpad-disabled"))]
        "touchpad-disabled-symbolic.svg",
        #[cfg(not(feature = "touchpad"))]
        "touchpad-symbolic.svg",
        #[cfg(not(feature = "town"))]
        "town-symbolic.svg",
        #[cfg(not(feature = "transform"))]
        "transform-symbolic.svg",
        #[cfg(not(feature = "transparent-background"))]
        "transparent-background-symbolic.svg",
        #[cfg(not(feature = "tree2"))]
        "tree2-symbolic.svg",
        #[cfg(not(feature = "tree"))]
        "tree-symbolic.svg",
        #[cfg(not(feature = "trophy"))]
        "trophy-symbolic.svg",
        #[cfg(not(feature = "tty"))]
        "tty-symbolic.svg",
        #[cfg(not(feature = "tv"))]
        "tv-symbolic.svg",
        #[cfg(not(feature = "ungroup"))]
        "ungroup-symbolic.svg",
        #[cfg(not(feature = "update"))]
        "update-symbolic.svg",
        #[cfg(not(feature = "up-large"))]
        "up-large-symbolic.svg",
        #[cfg(not(feature = "uppercase"))]
        "uppercase-symbolic.svg",
        #[cfg(not(feature = "ups"))]
        "ups-symbolic.svg",
        #[cfg(not(feature = "up"))]
        "up-symbolic.svg",
        #[cfg(not(feature = "usb-stick-round"))]
        "usb-stick-round-symbolic.svg",
        #[cfg(not(feature = "usb-stick"))]
        "usb-stick-symbolic.svg",
        #[cfg(not(feature = "user-trash-full"))]
        "user-trash-full-symbolic.svg",
        #[cfg(not(feature = "user-trash"))]
        "user-trash-symbolic.svg",
        #[cfg(not(feature = "video-camera"))]
        "video-camera-symbolic.svg",
        #[cfg(not(feature = "video-encoder"))]
        "video-encoder-symbolic.svg",
        #[cfg(not(feature = "view-columns"))]
        "view-columns-symbolic.svg",
        #[cfg(not(feature = "view-switcher"))]
        "view-switcher-symbolic.svg",
        #[cfg(not(feature = "violence2-none"))]
        "violence2-none-symbolic.svg",
        #[cfg(not(feature = "violence2"))]
        "violence2-symbolic.svg",
        #[cfg(not(feature = "violence3-none"))]
        "violence3-none-symbolic.svg",
        #[cfg(not(feature = "violence3"))]
        "violence3-symbolic.svg",
        #[cfg(not(feature = "violence-none"))]
        "violence-none-symbolic.svg",
        #[cfg(not(feature = "violence"))]
        "violence-symbolic.svg",
        #[cfg(not(feature = "vpn-caps-disabled"))]
        "vpn-caps-disabled-symbolic.svg",
        #[cfg(not(feature = "vpn-caps"))]
        "vpn-caps-symbolic.svg",
        #[cfg(not(feature = "wacom"))]
        "wacom-symbolic.svg",
        #[cfg(not(feature = "walking"))]
        "walking-symbolic.svg",
        #[cfg(not(feature = "wallet2"))]
        "wallet2-symbolic.svg",
        #[cfg(not(feature = "wallet3"))]
        "wallet3-symbolic.svg",
        #[cfg(not(feature = "wallet"))]
        "wallet-symbolic.svg",
        #[cfg(not(feature = "warning"))]
        "warning-symbolic.svg",
        #[cfg(not(feature = "weather-alert"))]
        "weather-alert-symbolic.svg",
        #[cfg(not(feature = "week"))]
        "week-symbolic.svg",
        #[cfg(not(feature = "weight2"))]
        "weight2-symbolic.svg",
        #[cfg(not(feature = "weight"))]
        "weight-symbolic.svg",
        #[cfg(not(feature = "wheat"))]
        "wheat-symbolic.svg",
        #[cfg(not(feature = "wheelchair-alt"))]
        "wheelchair-alt-symbolic.svg",
        #[cfg(not(feature = "wheelchair-limited"))]
        "wheelchair-limited-symbolic.svg",
        #[cfg(not(feature = "wheelchair"))]
        "wheelchair-symbolic.svg",
        #[cfg(not(feature = "window-flat"))]
        "window-flat-symbolic.svg",
        #[cfg(not(feature = "window-grow"))]
        "window-grow-symbolic.svg",
        #[cfg(not(feature = "window-scrolling"))]
        "window-scrolling-symbolic.svg",
        #[cfg(not(feature = "window-shrink"))]
        "window-shrink-symbolic.svg",
        #[cfg(not(feature = "window-sound-source"))]
        "window-sound-source-symbolic.svg",
        #[cfg(not(feature = "window"))]
        "window-symbolic.svg",
        #[cfg(not(feature = "windy"))]
        "windy-symbolic.svg",
        #[cfg(not(feature = "wine-glass"))]
        "wine-glass-symbolic.svg",
        #[cfg(not(feature = "work-week"))]
        "work-week-symbolic.svg",
        #[cfg(not(feature = "wrench"))]
        "wrench-symbolic.svg",
        #[cfg(not(feature = "wrench-wide"))]
        "wrench-wide-symbolic.svg",
        #[cfg(not(feature = "xbox-controller"))]
        "xbox-controller-symbolic.svg",
        #[cfg(not(feature = "x-circular"))]
        "x-circular-symbolic.svg",
        #[cfg(not(feature = "year-alt"))]
        "year-alt-symbolic.svg",
        #[cfg(not(feature = "year"))]
        "year-symbolic.svg",
        #[cfg(not(feature = "relm4"))]
        "relm4-symbolic.svg",
        // END AUTOGENERATED
    ];

    let data = GResourceBuilder::from_directory_with_extensions(
        PREFIX,
        ICONS.as_ref(),
        true,
        &["svg"],
        &ignore_list,
    )
    .unwrap()
    .build()
    .unwrap();

    let path = std::env::var("OUT_DIR").unwrap();
    let path: &std::path::Path = path.as_ref();
    std::fs::write(path.join(TARGET_FILE), data).unwrap();
}
