use std::path::Path;

use gvdb::gresource::{GResourceBuilder, GResourceFileData, PreprocessOptions};

const PREFIX: &str = "/relm4/icons/scalable/actions/";
const ICONS: &str = "icons";
const TARGET_FILE: &str = "resources.gresource";

fn main() {
    let icon_list = vec![
        // AUTOGENERATED - DO NOT EDIT
        #[cfg(feature = "C")]
        "C-symbolic.svg",
        #[cfg(feature = "about")]
        "about-symbolic.svg",
        #[cfg(feature = "address-book")]
        "address-book-symbolic.svg",
        #[cfg(feature = "address-book-alt")]
        "address-book-alt-symbolic.svg",
        #[cfg(feature = "airbrush-tool")]
        "airbrush-tool-symbolic.svg",
        #[cfg(feature = "alarm")]
        "alarm-symbolic.svg",
        #[cfg(feature = "align-tool")]
        "align-tool-symbolic.svg",
        #[cfg(feature = "anniversary")]
        "anniversary-symbolic.svg",
        #[cfg(feature = "annotation-sidebar")]
        "annotation-sidebar-symbolic.svg",
        #[cfg(feature = "app-icon-design")]
        "app-icon-design-symbolic.svg",
        #[cfg(feature = "application-x-firmware")]
        "application-x-firmware-symbolic.svg",
        #[cfg(feature = "archive")]
        "archive-symbolic.svg",
        #[cfg(feature = "arrow-into-box")]
        "arrow-into-box-symbolic.svg",
        #[cfg(feature = "arrow1-down")]
        "arrow1-down-symbolic.svg",
        #[cfg(feature = "arrow1-left")]
        "arrow1-left-symbolic.svg",
        #[cfg(feature = "arrow1-right")]
        "arrow1-right-symbolic.svg",
        #[cfg(feature = "arrow1-up")]
        "arrow1-up-symbolic.svg",
        #[cfg(feature = "arrow2-bottom-left")]
        "arrow2-bottom-left-symbolic.svg",
        #[cfg(feature = "arrow2-bottom-right")]
        "arrow2-bottom-right-symbolic.svg",
        #[cfg(feature = "arrow2-down")]
        "arrow2-down-symbolic.svg",
        #[cfg(feature = "arrow2-left")]
        "arrow2-left-symbolic.svg",
        #[cfg(feature = "arrow2-right")]
        "arrow2-right-symbolic.svg",
        #[cfg(feature = "arrow2-top-left")]
        "arrow2-top-left-symbolic.svg",
        #[cfg(feature = "arrow2-top-right")]
        "arrow2-top-right-symbolic.svg",
        #[cfg(feature = "arrow2-up")]
        "arrow2-up-symbolic.svg",
        #[cfg(feature = "arrow3-down")]
        "arrow3-down-symbolic.svg",
        #[cfg(feature = "arrow3-left")]
        "arrow3-left-symbolic.svg",
        #[cfg(feature = "arrow3-right")]
        "arrow3-right-symbolic.svg",
        #[cfg(feature = "arrow3-up")]
        "arrow3-up-symbolic.svg",
        #[cfg(feature = "arrows-questionmark")]
        "arrows-questionmark-symbolic.svg",
        #[cfg(feature = "assistive-listening")]
        "assistive-listening-symbolic.svg",
        #[cfg(feature = "attach-audio")]
        "attach-audio-symbolic.svg",
        #[cfg(feature = "audio-only")]
        "audio-only-symbolic.svg",
        #[cfg(feature = "audio-x-generic")]
        "audio-x-generic-symbolic.svg",
        #[cfg(feature = "auth-otp")]
        "auth-otp-symbolic.svg",
        #[cfg(feature = "axes-four-quadrants")]
        "axes-four-quadrants-symbolic.svg",
        #[cfg(feature = "axes-one-quadrant")]
        "axes-one-quadrant-symbolic.svg",
        #[cfg(feature = "axis-log-horizontal")]
        "axis-log-horizontal-symbolic.svg",
        #[cfg(feature = "axis-log-vertical")]
        "axis-log-vertical-symbolic.svg",
        #[cfg(feature = "background-app")]
        "background-app-symbolic.svg",
        #[cfg(feature = "background-app-ghost")]
        "background-app-ghost-symbolic.svg",
        #[cfg(feature = "background-app-rectangular")]
        "background-app-rectangular-symbolic.svg",
        #[cfg(feature = "background-app-sleepyface")]
        "background-app-sleepyface-symbolic.svg",
        #[cfg(feature = "bank")]
        "bank-symbolic.svg",
        #[cfg(feature = "banner")]
        "banner-symbolic.svg",
        #[cfg(feature = "barbecue")]
        "barbecue-symbolic.svg",
        #[cfg(feature = "baseball")]
        "baseball-symbolic.svg",
        #[cfg(feature = "battery")]
        "battery-symbolic.svg",
        #[cfg(feature = "bear")]
        "bear-symbolic.svg",
        #[cfg(feature = "bed")]
        "bed-symbolic.svg",
        #[cfg(feature = "bell")]
        "bell-symbolic.svg",
        #[cfg(feature = "bell-large")]
        "bell-large-symbolic.svg",
        #[cfg(feature = "bell-large-none")]
        "bell-large-none-symbolic.svg",
        #[cfg(feature = "bell-none")]
        "bell-none-symbolic.svg",
        #[cfg(feature = "bell-outline")]
        "bell-outline-symbolic.svg",
        #[cfg(feature = "bell-outline-none")]
        "bell-outline-none-symbolic.svg",
        #[cfg(feature = "bench")]
        "bench-symbolic.svg",
        #[cfg(feature = "big-dot")]
        "big-dot-symbolic.svg",
        #[cfg(feature = "big-x")]
        "big-x-symbolic.svg",
        #[cfg(feature = "birthday")]
        "birthday-symbolic.svg",
        #[cfg(feature = "blend-tool")]
        "blend-tool-symbolic.svg",
        #[cfg(feature = "blind")]
        "blind-symbolic.svg",
        #[cfg(feature = "bluetooth")]
        "bluetooth-symbolic.svg",
        #[cfg(feature = "bluetooth-none")]
        "bluetooth-none-symbolic.svg",
        #[cfg(feature = "blur")]
        "blur-symbolic.svg",
        #[cfg(feature = "blur-alt")]
        "blur-alt-symbolic.svg",
        #[cfg(feature = "body")]
        "body-symbolic.svg",
        #[cfg(feature = "bottom")]
        "bottom-symbolic.svg",
        #[cfg(feature = "bottom-large")]
        "bottom-large-symbolic.svg",
        #[cfg(feature = "box-down")]
        "box-down-symbolic.svg",
        #[cfg(feature = "box-left")]
        "box-left-symbolic.svg",
        #[cfg(feature = "box-right")]
        "box-right-symbolic.svg",
        #[cfg(feature = "box-up")]
        "box-up-symbolic.svg",
        #[cfg(feature = "branch")]
        "branch-symbolic.svg",
        #[cfg(feature = "bread")]
        "bread-symbolic.svg",
        #[cfg(feature = "break-point")]
        "break-point-symbolic.svg",
        #[cfg(feature = "briefcase")]
        "briefcase-symbolic.svg",
        #[cfg(feature = "broken-camera-inverse")]
        "broken-camera-inverse-symbolic.svg",
        #[cfg(feature = "broken-playback")]
        "broken-playback-symbolic.svg",
        #[cfg(feature = "broken-video")]
        "broken-video-symbolic.svg",
        #[cfg(feature = "brush")]
        "brush-symbolic.svg",
        #[cfg(feature = "brush-monitor")]
        "brush-monitor-symbolic.svg",
        #[cfg(feature = "bug")]
        "bug-symbolic.svg",
        #[cfg(feature = "build")]
        "build-symbolic.svg",
        #[cfg(feature = "build-alt")]
        "build-alt-symbolic.svg",
        #[cfg(feature = "build-configure")]
        "build-configure-symbolic.svg",
        #[cfg(feature = "building")]
        "building-symbolic.svg",
        #[cfg(feature = "bus")]
        "bus-symbolic.svg",
        #[cfg(feature = "cafe")]
        "cafe-symbolic.svg",
        #[cfg(feature = "cage")]
        "cage-symbolic.svg",
        #[cfg(feature = "call-add")]
        "call-add-symbolic.svg",
        #[cfg(feature = "call-incoming")]
        "call-incoming-symbolic.svg",
        #[cfg(feature = "call-made")]
        "call-made-symbolic.svg",
        #[cfg(feature = "call-merge")]
        "call-merge-symbolic.svg",
        #[cfg(feature = "call-missed")]
        "call-missed-symbolic.svg",
        #[cfg(feature = "call-missed-incoming")]
        "call-missed-incoming-symbolic.svg",
        #[cfg(feature = "call-missed-outgoing")]
        "call-missed-outgoing-symbolic.svg",
        #[cfg(feature = "call-outgoing")]
        "call-outgoing-symbolic.svg",
        #[cfg(feature = "call-outgoing-unsuccessful")]
        "call-outgoing-unsuccessful-symbolic.svg",
        #[cfg(feature = "call-received")]
        "call-received-symbolic.svg",
        #[cfg(feature = "call-ring")]
        "call-ring-symbolic.svg",
        #[cfg(feature = "call-ringer-silenced")]
        "call-ringer-silenced-symbolic.svg",
        #[cfg(feature = "call-split")]
        "call-split-symbolic.svg",
        #[cfg(feature = "camera")]
        "camera-symbolic.svg",
        #[cfg(feature = "camera-broken")]
        "camera-broken-symbolic.svg",
        #[cfg(feature = "camera-dead")]
        "camera-dead-symbolic.svg",
        #[cfg(feature = "camera-flash")]
        "camera-flash-symbolic.svg",
        #[cfg(feature = "camera-flash-auto")]
        "camera-flash-auto-symbolic.svg",
        #[cfg(feature = "camera-flash-disabled")]
        "camera-flash-disabled-symbolic.svg",
        #[cfg(feature = "camera-focus")]
        "camera-focus-symbolic.svg",
        #[cfg(feature = "camera-grid")]
        "camera-grid-symbolic.svg",
        #[cfg(feature = "camera-iso")]
        "camera-iso-symbolic.svg",
        #[cfg(feature = "camera-iso-alt")]
        "camera-iso-alt-symbolic.svg",
        #[cfg(feature = "camera-large")]
        "camera-large-symbolic.svg",
        #[cfg(feature = "camera-shutter")]
        "camera-shutter-symbolic.svg",
        #[cfg(feature = "camera-static")]
        "camera-static-symbolic.svg",
        #[cfg(feature = "camera-static-inverse")]
        "camera-static-inverse-symbolic.svg",
        #[cfg(feature = "camera-toggle")]
        "camera-toggle-symbolic.svg",
        #[cfg(feature = "cameras")]
        "cameras-symbolic.svg",
        #[cfg(feature = "carousel")]
        "carousel-symbolic.svg",
        #[cfg(feature = "cat")]
        "cat-symbolic.svg",
        #[cfg(feature = "cat-sleeping")]
        "cat-sleeping-symbolic.svg",
        #[cfg(feature = "cd")]
        "cd-symbolic.svg",
        #[cfg(feature = "center")]
        "center-symbolic.svg",
        #[cfg(feature = "chain-link")]
        "chain-link-symbolic.svg",
        #[cfg(feature = "chain-link-loose")]
        "chain-link-loose-symbolic.svg",
        #[cfg(feature = "charge")]
        "charge-symbolic.svg",
        #[cfg(feature = "chat")]
        "chat-symbolic.svg",
        #[cfg(feature = "chat-bubble-emtpy")]
        "chat-bubble-emtpy-symbolic.svg",
        #[cfg(feature = "chat-bubble-text")]
        "chat-bubble-text-symbolic.svg",
        #[cfg(feature = "chat-bubble-text-inverted")]
        "chat-bubble-text-inverted-symbolic.svg",
        #[cfg(feature = "chat-bubbles-empty-inverted")]
        "chat-bubbles-empty-inverted-symbolic.svg",
        #[cfg(feature = "chat-bubbles-emtpy")]
        "chat-bubbles-emtpy-symbolic.svg",
        #[cfg(feature = "chat-bubbles-text")]
        "chat-bubbles-text-symbolic.svg",
        #[cfg(feature = "chat-bubbles-text-inverted")]
        "chat-bubbles-text-inverted-symbolic.svg",
        #[cfg(feature = "chat-none")]
        "chat-none-symbolic.svg",
        #[cfg(feature = "check-plain")]
        "check-plain-symbolic.svg",
        #[cfg(feature = "check-round-outline")]
        "check-round-outline-symbolic.svg",
        #[cfg(feature = "check-round-outline-whole")]
        "check-round-outline-whole-symbolic.svg",
        #[cfg(feature = "check-round-outline2")]
        "check-round-outline2-symbolic.svg",
        #[cfg(feature = "checkerboard")]
        "checkerboard-symbolic.svg",
        #[cfg(feature = "checkerboard-big")]
        "checkerboard-big-symbolic.svg",
        #[cfg(feature = "checkmark")]
        "checkmark-symbolic.svg",
        #[cfg(feature = "checkmark-large")]
        "checkmark-large-symbolic.svg",
        #[cfg(feature = "checkmark-small")]
        "checkmark-small-symbolic.svg",
        #[cfg(feature = "christmas")]
        "christmas-symbolic.svg",
        #[cfg(feature = "cigarette")]
        "cigarette-symbolic.svg",
        #[cfg(feature = "cigarette-none")]
        "cigarette-none-symbolic.svg",
        #[cfg(feature = "circle-filled")]
        "circle-filled-symbolic.svg",
        #[cfg(feature = "circle-outline-thick")]
        "circle-outline-thick-symbolic.svg",
        #[cfg(feature = "circle-outline-thin")]
        "circle-outline-thin-symbolic.svg",
        #[cfg(feature = "city")]
        "city-symbolic.svg",
        #[cfg(feature = "clipboard")]
        "clipboard-symbolic.svg",
        #[cfg(feature = "clock")]
        "clock-symbolic.svg",
        #[cfg(feature = "clock-alt")]
        "clock-alt-symbolic.svg",
        #[cfg(feature = "closed-captioning")]
        "closed-captioning-symbolic.svg",
        #[cfg(feature = "cloud-disabled")]
        "cloud-disabled-symbolic.svg",
        #[cfg(feature = "cloud-filled")]
        "cloud-filled-symbolic.svg",
        #[cfg(feature = "cloud-outline-thick")]
        "cloud-outline-thick-symbolic.svg",
        #[cfg(feature = "cloud-outline-thin")]
        "cloud-outline-thin-symbolic.svg",
        #[cfg(feature = "clouds")]
        "clouds-symbolic.svg",
        #[cfg(feature = "clouds-outline")]
        "clouds-outline-symbolic.svg",
        #[cfg(feature = "cocktail")]
        "cocktail-symbolic.svg",
        #[cfg(feature = "code")]
        "code-symbolic.svg",
        #[cfg(feature = "coin")]
        "coin-symbolic.svg",
        #[cfg(feature = "color")]
        "color-symbolic.svg",
        #[cfg(feature = "color-picker")]
        "color-picker-symbolic.svg",
        #[cfg(feature = "colorimeter-colorhug")]
        "colorimeter-colorhug-symbolic.svg",
        #[cfg(feature = "columns")]
        "columns-symbolic.svg",
        #[cfg(feature = "compass")]
        "compass-symbolic.svg",
        #[cfg(feature = "compass-alt")]
        "compass-alt-symbolic.svg",
        #[cfg(feature = "compass-wind")]
        "compass-wind-symbolic.svg",
        #[cfg(feature = "computer")]
        "computer-symbolic.svg",
        #[cfg(feature = "computer-chip")]
        "computer-chip-symbolic.svg",
        #[cfg(feature = "configure")]
        "configure-symbolic.svg",
        #[cfg(feature = "container-terminal")]
        "container-terminal-symbolic.svg",
        #[cfg(feature = "controls")]
        "controls-symbolic.svg",
        #[cfg(feature = "controls-big")]
        "controls-big-symbolic.svg",
        #[cfg(feature = "copy")]
        "copy-symbolic.svg",
        #[cfg(feature = "cow")]
        "cow-symbolic.svg",
        #[cfg(feature = "credit-card")]
        "credit-card-symbolic.svg",
        #[cfg(feature = "crop")]
        "crop-symbolic.svg",
        #[cfg(feature = "cross")]
        "cross-symbolic.svg",
        #[cfg(feature = "cross-filled")]
        "cross-filled-symbolic.svg",
        #[cfg(feature = "cross-filled-large")]
        "cross-filled-large-symbolic.svg",
        #[cfg(feature = "cross-large")]
        "cross-large-symbolic.svg",
        #[cfg(feature = "crossword-clue-across")]
        "crossword-clue-across-symbolic.svg",
        #[cfg(feature = "crossword-clue-down")]
        "crossword-clue-down-symbolic.svg",
        #[cfg(feature = "cut")]
        "cut-symbolic.svg",
        #[cfg(feature = "cycling")]
        "cycling-symbolic.svg",
        #[cfg(feature = "dark-mode")]
        "dark-mode-symbolic.svg",
        #[cfg(feature = "deaf")]
        "deaf-symbolic.svg",
        #[cfg(feature = "deck")]
        "deck-symbolic.svg",
        #[cfg(feature = "decode")]
        "decode-symbolic.svg",
        #[cfg(feature = "derivative")]
        "derivative-symbolic.svg",
        #[cfg(feature = "derivative2")]
        "derivative2-symbolic.svg",
        #[cfg(feature = "detach-audio")]
        "detach-audio-symbolic.svg",
        #[cfg(feature = "diagnostics")]
        "diagnostics-symbolic.svg",
        #[cfg(feature = "dialog")]
        "dialog-symbolic.svg",
        #[cfg(feature = "dialpad")]
        "dialpad-symbolic.svg",
        #[cfg(feature = "diamond-filled")]
        "diamond-filled-symbolic.svg",
        #[cfg(feature = "diamond-outline-thick")]
        "diamond-outline-thick-symbolic.svg",
        #[cfg(feature = "diamond-outline-thin")]
        "diamond-outline-thin-symbolic.svg",
        #[cfg(feature = "dice")]
        "dice-symbolic.svg",
        #[cfg(feature = "dice2")]
        "dice2-symbolic.svg",
        #[cfg(feature = "dice3")]
        "dice3-symbolic.svg",
        #[cfg(feature = "dictionary")]
        "dictionary-symbolic.svg",
        #[cfg(feature = "discover")]
        "discover-symbolic.svg",
        #[cfg(feature = "display")]
        "display-symbolic.svg",
        #[cfg(feature = "display-projector")]
        "display-projector-symbolic.svg",
        #[cfg(feature = "display-with-window")]
        "display-with-window-symbolic.svg",
        #[cfg(feature = "do-not-distrub")]
        "do-not-distrub-symbolic.svg",
        #[cfg(feature = "dock")]
        "dock-symbolic.svg",
        #[cfg(feature = "dock-bottom")]
        "dock-bottom-symbolic.svg",
        #[cfg(feature = "dock-left")]
        "dock-left-symbolic.svg",
        #[cfg(feature = "dock-right")]
        "dock-right-symbolic.svg",
        #[cfg(feature = "dock-top")]
        "dock-top-symbolic.svg",
        #[cfg(feature = "dock-usb")]
        "dock-usb-symbolic.svg",
        #[cfg(feature = "dog")]
        "dog-symbolic.svg",
        #[cfg(feature = "dot")]
        "dot-symbolic.svg",
        #[cfg(feature = "dotted-box")]
        "dotted-box-symbolic.svg",
        #[cfg(feature = "down")]
        "down-symbolic.svg",
        #[cfg(feature = "down-large")]
        "down-large-symbolic.svg",
        #[cfg(feature = "drag-n-drop")]
        "drag-n-drop-symbolic.svg",
        #[cfg(feature = "drawer")]
        "drawer-symbolic.svg",
        #[cfg(feature = "drinks")]
        "drinks-symbolic.svg",
        #[cfg(feature = "driving")]
        "driving-symbolic.svg",
        #[cfg(feature = "drone")]
        "drone-symbolic.svg",
        #[cfg(feature = "drop-hollow")]
        "drop-hollow-symbolic.svg",
        #[cfg(feature = "earth")]
        "earth-symbolic.svg",
        #[cfg(feature = "edit")]
        "edit-symbolic.svg",
        #[cfg(feature = "edit-select-all")]
        "edit-select-all-symbolic.svg",
        #[cfg(feature = "edit-select-none")]
        "edit-select-none-symbolic.svg",
        #[cfg(feature = "editor")]
        "editor-symbolic.svg",
        #[cfg(feature = "egg")]
        "egg-symbolic.svg",
        #[cfg(feature = "eject")]
        "eject-symbolic.svg",
        #[cfg(feature = "eject-large")]
        "eject-large-symbolic.svg",
        #[cfg(feature = "electric-car")]
        "electric-car-symbolic.svg",
        #[cfg(feature = "encode")]
        "encode-symbolic.svg",
        #[cfg(feature = "encoder-knob")]
        "encoder-knob-symbolic.svg",
        #[cfg(feature = "entry-clear")]
        "entry-clear-symbolic.svg",
        #[cfg(feature = "eraser")]
        "eraser-symbolic.svg",
        #[cfg(feature = "eraser2")]
        "eraser2-symbolic.svg",
        #[cfg(feature = "eraser3")]
        "eraser3-symbolic.svg",
        #[cfg(feature = "eraser4")]
        "eraser4-symbolic.svg",
        #[cfg(feature = "eraser5")]
        "eraser5-symbolic.svg",
        #[cfg(feature = "error")]
        "error-symbolic.svg",
        #[cfg(feature = "execute-from")]
        "execute-from-symbolic.svg",
        #[cfg(feature = "execute-to")]
        "execute-to-symbolic.svg",
        #[cfg(feature = "explore")]
        "explore-symbolic.svg",
        #[cfg(feature = "explore2")]
        "explore2-symbolic.svg",
        #[cfg(feature = "explore2-large")]
        "explore2-large-symbolic.svg",
        #[cfg(feature = "external-devices")]
        "external-devices-symbolic.svg",
        #[cfg(feature = "external-link")]
        "external-link-symbolic.svg",
        #[cfg(feature = "eye-closed")]
        "eye-closed-symbolic.svg",
        #[cfg(feature = "eye-closed-negative")]
        "eye-closed-negative-symbolic.svg",
        #[cfg(feature = "eye-not-looking")]
        "eye-not-looking-symbolic.svg",
        #[cfg(feature = "eye-open")]
        "eye-open-symbolic.svg",
        #[cfg(feature = "eye-open-negative")]
        "eye-open-negative-symbolic.svg",
        #[cfg(feature = "eye-open-negative-filled")]
        "eye-open-negative-filled-symbolic.svg",
        #[cfg(feature = "face-unlock")]
        "face-unlock-symbolic.svg",
        #[cfg(feature = "fast-food")]
        "fast-food-symbolic.svg",
        #[cfg(feature = "fast-fourier-transform")]
        "fast-fourier-transform-symbolic.svg",
        #[cfg(feature = "fax")]
        "fax-symbolic.svg",
        #[cfg(feature = "feet")]
        "feet-symbolic.svg",
        #[cfg(feature = "few-clouds")]
        "few-clouds-symbolic.svg",
        #[cfg(feature = "few-clouds-night")]
        "few-clouds-night-symbolic.svg",
        #[cfg(feature = "few-clouds-outline")]
        "few-clouds-outline-symbolic.svg",
        #[cfg(feature = "file-cabinet")]
        "file-cabinet-symbolic.svg",
        #[cfg(feature = "file-manager")]
        "file-manager-symbolic.svg",
        #[cfg(feature = "fill-tool")]
        "fill-tool-symbolic.svg",
        #[cfg(feature = "fingerprint")]
        "fingerprint-symbolic.svg",
        #[cfg(feature = "fingerprint-authentication")]
        "fingerprint-authentication-symbolic.svg",
        #[cfg(feature = "fingerprint2")]
        "fingerprint2-symbolic.svg",
        #[cfg(feature = "fire")]
        "fire-symbolic.svg",
        #[cfg(feature = "fire2")]
        "fire2-symbolic.svg",
        #[cfg(feature = "firmware-update")]
        "firmware-update-symbolic.svg",
        #[cfg(feature = "first")]
        "first-symbolic.svg",
        #[cfg(feature = "first-large")]
        "first-large-symbolic.svg",
        #[cfg(feature = "fish")]
        "fish-symbolic.svg",
        #[cfg(feature = "flag-filled")]
        "flag-filled-symbolic.svg",
        #[cfg(feature = "flag-outline-thick")]
        "flag-outline-thick-symbolic.svg",
        #[cfg(feature = "flag-outline-thin")]
        "flag-outline-thin-symbolic.svg",
        #[cfg(feature = "flap")]
        "flap-symbolic.svg",
        #[cfg(feature = "flash-memory")]
        "flash-memory-symbolic.svg",
        #[cfg(feature = "flashlight")]
        "flashlight-symbolic.svg",
        #[cfg(feature = "flashlight-none")]
        "flashlight-none-symbolic.svg",
        #[cfg(feature = "flatpak")]
        "flatpak-symbolic.svg",
        #[cfg(feature = "floppy")]
        "floppy-symbolic.svg",
        #[cfg(feature = "flying")]
        "flying-symbolic.svg",
        #[cfg(feature = "flying2")]
        "flying2-symbolic.svg",
        #[cfg(feature = "fog")]
        "fog-symbolic.svg",
        #[cfg(feature = "folder-remote")]
        "folder-remote-symbolic.svg",
        #[cfg(feature = "font-x-generic")]
        "font-x-generic-symbolic.svg",
        #[cfg(feature = "football-american")]
        "football-american-symbolic.svg",
        #[cfg(feature = "fuel")]
        "fuel-symbolic.svg",
        #[cfg(feature = "function-exponential")]
        "function-exponential-symbolic.svg",
        #[cfg(feature = "function-linear")]
        "function-linear-symbolic.svg",
        #[cfg(feature = "function-parable")]
        "function-parable-symbolic.svg",
        #[cfg(feature = "function-parable-horizontal")]
        "function-parable-horizontal-symbolic.svg",
        #[cfg(feature = "function-third-order")]
        "function-third-order-symbolic.svg",
        #[cfg(feature = "function-third-order-horizontal")]
        "function-third-order-horizontal-symbolic.svg",
        #[cfg(feature = "funnel")]
        "funnel-symbolic.svg",
        #[cfg(feature = "funnel-outline")]
        "funnel-outline-symbolic.svg",
        #[cfg(feature = "gamepad")]
        "gamepad-symbolic.svg",
        #[cfg(feature = "gamepad2")]
        "gamepad2-symbolic.svg",
        #[cfg(feature = "garlic")]
        "garlic-symbolic.svg",
        #[cfg(feature = "gear")]
        "gear-symbolic.svg",
        #[cfg(feature = "general-properties")]
        "general-properties-symbolic.svg",
        #[cfg(feature = "git")]
        "git-symbolic.svg",
        #[cfg(feature = "git-branch")]
        "git-branch-symbolic.svg",
        #[cfg(feature = "git-merge")]
        "git-merge-symbolic.svg",
        #[cfg(feature = "globe")]
        "globe-symbolic.svg",
        #[cfg(feature = "globe-alt")]
        "globe-alt-symbolic.svg",
        #[cfg(feature = "globe-alt2")]
        "globe-alt2-symbolic.svg",
        #[cfg(feature = "golf")]
        "golf-symbolic.svg",
        #[cfg(feature = "graph")]
        "graph-symbolic.svg",
        #[cfg(feature = "graph2")]
        "graph2-symbolic.svg",
        #[cfg(feature = "graveyard")]
        "graveyard-symbolic.svg",
        #[cfg(feature = "grid")]
        "grid-symbolic.svg",
        #[cfg(feature = "grid-filled")]
        "grid-filled-symbolic.svg",
        #[cfg(feature = "grid-large")]
        "grid-large-symbolic.svg",
        #[cfg(feature = "group")]
        "group-symbolic.svg",
        #[cfg(feature = "h")]
        "h-symbolic.svg",
        #[cfg(feature = "hand-fist")]
        "hand-fist-symbolic.svg",
        #[cfg(feature = "hand-fist-none")]
        "hand-fist-none-symbolic.svg",
        #[cfg(feature = "hand-middle-finger")]
        "hand-middle-finger-symbolic.svg",
        #[cfg(feature = "hand-open")]
        "hand-open-symbolic.svg",
        #[cfg(feature = "hand-point")]
        "hand-point-symbolic.svg",
        #[cfg(feature = "hand-point-horizontal")]
        "hand-point-horizontal-symbolic.svg",
        #[cfg(feature = "hand-point-left")]
        "hand-point-left-symbolic.svg",
        #[cfg(feature = "hand-point-right")]
        "hand-point-right-symbolic.svg",
        #[cfg(feature = "hand-touch")]
        "hand-touch-symbolic.svg",
        #[cfg(feature = "handshake")]
        "handshake-symbolic.svg",
        #[cfg(feature = "harddisk")]
        "harddisk-symbolic.svg",
        #[cfg(feature = "harddisk-inverted")]
        "harddisk-inverted-symbolic.svg",
        #[cfg(feature = "headphones")]
        "headphones-symbolic.svg",
        #[cfg(feature = "headset")]
        "headset-symbolic.svg",
        #[cfg(feature = "heal")]
        "heal-symbolic.svg",
        #[cfg(feature = "heart-broken")]
        "heart-broken-symbolic.svg",
        #[cfg(feature = "heart-filled")]
        "heart-filled-symbolic.svg",
        #[cfg(feature = "heart-outline-thick")]
        "heart-outline-thick-symbolic.svg",
        #[cfg(feature = "heart-outline-thin")]
        "heart-outline-thin-symbolic.svg",
        #[cfg(feature = "hig")]
        "hig-symbolic.svg",
        #[cfg(feature = "history-undo")]
        "history-undo-symbolic.svg",
        #[cfg(feature = "hockey")]
        "hockey-symbolic.svg",
        #[cfg(feature = "horizontal-arrows")]
        "horizontal-arrows-symbolic.svg",
        #[cfg(feature = "horizontal-arrows-disabled")]
        "horizontal-arrows-disabled-symbolic.svg",
        #[cfg(feature = "horizontal-arrows-left")]
        "horizontal-arrows-left-symbolic.svg",
        #[cfg(feature = "horizontal-arrows-none")]
        "horizontal-arrows-none-symbolic.svg",
        #[cfg(feature = "horizontal-arrows-one-way")]
        "horizontal-arrows-one-way-symbolic.svg",
        #[cfg(feature = "horizontal-arrows-right")]
        "horizontal-arrows-right-symbolic.svg",
        #[cfg(feature = "hospital")]
        "hospital-symbolic.svg",
        #[cfg(feature = "hospital-sign")]
        "hospital-sign-symbolic.svg",
        #[cfg(feature = "hourglass")]
        "hourglass-symbolic.svg",
        #[cfg(feature = "image")]
        "image-symbolic.svg",
        #[cfg(feature = "image-adjust-brightness")]
        "image-adjust-brightness-symbolic.svg",
        #[cfg(feature = "image-adjust-contrast")]
        "image-adjust-contrast-symbolic.svg",
        #[cfg(feature = "image-adjust-exposure")]
        "image-adjust-exposure-symbolic.svg",
        #[cfg(feature = "image-adjust-highlights")]
        "image-adjust-highlights-symbolic.svg",
        #[cfg(feature = "image-adjust-shadows")]
        "image-adjust-shadows-symbolic.svg",
        #[cfg(feature = "image-alt")]
        "image-alt-symbolic.svg",
        #[cfg(feature = "image-missing")]
        "image-missing-symbolic.svg",
        #[cfg(feature = "image-missing-round")]
        "image-missing-round-symbolic.svg",
        #[cfg(feature = "image-print")]
        "image-print-symbolic.svg",
        #[cfg(feature = "image-round")]
        "image-round-symbolic.svg",
        #[cfg(feature = "inbox")]
        "inbox-symbolic.svg",
        #[cfg(feature = "info")]
        "info-symbolic.svg",
        #[cfg(feature = "ink-tool")]
        "ink-tool-symbolic.svg",
        #[cfg(feature = "integral")]
        "integral-symbolic.svg",
        #[cfg(feature = "integral2")]
        "integral2-symbolic.svg",
        #[cfg(feature = "integral3")]
        "integral3-symbolic.svg",
        #[cfg(feature = "inverse-fast-fourier-transform")]
        "inverse-fast-fourier-transform-symbolic.svg",
        #[cfg(feature = "invert-colors")]
        "invert-colors-symbolic.svg",
        #[cfg(feature = "iphone")]
        "iphone-symbolic.svg",
        #[cfg(feature = "ipod")]
        "ipod-symbolic.svg",
        #[cfg(feature = "issue")]
        "issue-symbolic.svg",
        #[cfg(feature = "item-missing")]
        "item-missing-symbolic.svg",
        #[cfg(feature = "joined-displays")]
        "joined-displays-symbolic.svg",
        #[cfg(feature = "junk")]
        "junk-symbolic.svg",
        #[cfg(feature = "junk-alt")]
        "junk-alt-symbolic.svg",
        #[cfg(feature = "key")]
        "key-symbolic.svg",
        #[cfg(feature = "key2")]
        "key2-symbolic.svg",
        #[cfg(feature = "keyboard")]
        "keyboard-symbolic.svg",
        #[cfg(feature = "keyboard-caps-lock")]
        "keyboard-caps-lock-symbolic.svg",
        #[cfg(feature = "keyboard-caps-lock-filled")]
        "keyboard-caps-lock-filled-symbolic.svg",
        #[cfg(feature = "keyboard-caps-lock-wide")]
        "keyboard-caps-lock-wide-symbolic.svg",
        #[cfg(feature = "keyboard-caps-lock-wide-filled")]
        "keyboard-caps-lock-wide-filled-symbolic.svg",
        #[cfg(feature = "keyboard-enter")]
        "keyboard-enter-symbolic.svg",
        #[cfg(feature = "keyboard-extend")]
        "keyboard-extend-symbolic.svg",
        #[cfg(feature = "keyboard-hide")]
        "keyboard-hide-symbolic.svg",
        #[cfg(feature = "keyboard-layout")]
        "keyboard-layout-symbolic.svg",
        #[cfg(feature = "keyboard-layout-filled")]
        "keyboard-layout-filled-symbolic.svg",
        #[cfg(feature = "keyboard-option")]
        "keyboard-option-symbolic.svg",
        #[cfg(feature = "keyboard-retract")]
        "keyboard-retract-symbolic.svg",
        #[cfg(feature = "keyboard-shift")]
        "keyboard-shift-symbolic.svg",
        #[cfg(feature = "keyboard-shift-filled")]
        "keyboard-shift-filled-symbolic.svg",
        #[cfg(feature = "keyboard-shortcuts")]
        "keyboard-shortcuts-symbolic.svg",
        #[cfg(feature = "keyboard2")]
        "keyboard2-symbolic.svg",
        #[cfg(feature = "keyboard3")]
        "keyboard3-symbolic.svg",
        #[cfg(feature = "lan")]
        "lan-symbolic.svg",
        #[cfg(feature = "language")]
        "language-symbolic.svg",
        #[cfg(feature = "large-brush")]
        "large-brush-symbolic.svg",
        #[cfg(feature = "larger-brush")]
        "larger-brush-symbolic.svg",
        #[cfg(feature = "last")]
        "last-symbolic.svg",
        #[cfg(feature = "last-large")]
        "last-large-symbolic.svg",
        #[cfg(feature = "leaflet")]
        "leaflet-symbolic.svg",
        #[cfg(feature = "left")]
        "left-symbolic.svg",
        #[cfg(feature = "left-large")]
        "left-large-symbolic.svg",
        #[cfg(feature = "library")]
        "library-symbolic.svg",
        #[cfg(feature = "library-artists")]
        "library-artists-symbolic.svg",
        #[cfg(feature = "library-music")]
        "library-music-symbolic.svg",
        #[cfg(feature = "lightbulb")]
        "lightbulb-symbolic.svg",
        #[cfg(feature = "list")]
        "list-symbolic.svg",
        #[cfg(feature = "list-compact")]
        "list-compact-symbolic.svg",
        #[cfg(feature = "list-large")]
        "list-large-symbolic.svg",
        #[cfg(feature = "loaf")]
        "loaf-symbolic.svg",
        #[cfg(feature = "lock-small")]
        "lock-small-symbolic.svg",
        #[cfg(feature = "lock-small-open")]
        "lock-small-open-symbolic.svg",
        #[cfg(feature = "loupe")]
        "loupe-symbolic.svg",
        #[cfg(feature = "loupe-large")]
        "loupe-large-symbolic.svg",
        #[cfg(feature = "loupe-with-arrow")]
        "loupe-with-arrow-symbolic.svg",
        #[cfg(feature = "loupe-with-heart")]
        "loupe-with-heart-symbolic.svg",
        #[cfg(feature = "low-vision")]
        "low-vision-symbolic.svg",
        #[cfg(feature = "magic-wand")]
        "magic-wand-symbolic.svg",
        #[cfg(feature = "mail")]
        "mail-symbolic.svg",
        #[cfg(feature = "mail-archive")]
        "mail-archive-symbolic.svg",
        #[cfg(feature = "mail-read")]
        "mail-read-symbolic.svg",
        #[cfg(feature = "mail-secure")]
        "mail-secure-symbolic.svg",
        #[cfg(feature = "mailbox")]
        "mailbox-symbolic.svg",
        #[cfg(feature = "map")]
        "map-symbolic.svg",
        #[cfg(feature = "map-marker")]
        "map-marker-symbolic.svg",
        #[cfg(feature = "map-marker-2")]
        "map-marker-2-symbolic.svg",
        #[cfg(feature = "mark")]
        "mark-symbolic.svg",
        #[cfg(feature = "mark2")]
        "mark2-symbolic.svg",
        #[cfg(feature = "markdown")]
        "markdown-symbolic.svg",
        #[cfg(feature = "marker")]
        "marker-symbolic.svg",
        #[cfg(feature = "meat")]
        "meat-symbolic.svg",
        #[cfg(feature = "meeting")]
        "meeting-symbolic.svg",
        #[cfg(feature = "menu")]
        "menu-symbolic.svg",
        #[cfg(feature = "menu-large")]
        "menu-large-symbolic.svg",
        #[cfg(feature = "merge")]
        "merge-symbolic.svg",
        #[cfg(feature = "microphone")]
        "microphone-symbolic.svg",
        #[cfg(feature = "microphone2")]
        "microphone2-symbolic.svg",
        #[cfg(feature = "minus")]
        "minus-symbolic.svg",
        #[cfg(feature = "minus-large")]
        "minus-large-symbolic.svg",
        #[cfg(feature = "mobile-network")]
        "mobile-network-symbolic.svg",
        #[cfg(feature = "modem")]
        "modem-symbolic.svg",
        #[cfg(feature = "money")]
        "money-symbolic.svg",
        #[cfg(feature = "money-clip")]
        "money-clip-symbolic.svg",
        #[cfg(feature = "money-none")]
        "money-none-symbolic.svg",
        #[cfg(feature = "monitor-pick")]
        "monitor-pick-symbolic.svg",
        #[cfg(feature = "month")]
        "month-symbolic.svg",
        #[cfg(feature = "moon")]
        "moon-symbolic.svg",
        #[cfg(feature = "moon-alt")]
        "moon-alt-symbolic.svg",
        #[cfg(feature = "moon-alt2")]
        "moon-alt2-symbolic.svg",
        #[cfg(feature = "moon-clouds-outline")]
        "moon-clouds-outline-symbolic.svg",
        #[cfg(feature = "moon-filled")]
        "moon-filled-symbolic.svg",
        #[cfg(feature = "moon-outline")]
        "moon-outline-symbolic.svg",
        #[cfg(feature = "mountain")]
        "mountain-symbolic.svg",
        #[cfg(feature = "mouse")]
        "mouse-symbolic.svg",
        #[cfg(feature = "mouse-wireless")]
        "mouse-wireless-symbolic.svg",
        #[cfg(feature = "mouse-wireless-disabled")]
        "mouse-wireless-disabled-symbolic.svg",
        #[cfg(feature = "mouse-wireless-disabled-filled")]
        "mouse-wireless-disabled-filled-symbolic.svg",
        #[cfg(feature = "mouse-wireless-filled")]
        "mouse-wireless-filled-symbolic.svg",
        #[cfg(feature = "mouse-with-smaller-scrollwheel")]
        "mouse-with-smaller-scrollwheel-symbolic.svg",
        #[cfg(feature = "move-to-window")]
        "move-to-window-symbolic.svg",
        #[cfg(feature = "move-tool")]
        "move-tool-symbolic.svg",
        #[cfg(feature = "multitasking")]
        "multitasking-symbolic.svg",
        #[cfg(feature = "multitasking-windows")]
        "multitasking-windows-symbolic.svg",
        #[cfg(feature = "museum")]
        "museum-symbolic.svg",
        #[cfg(feature = "music-artist")]
        "music-artist-symbolic.svg",
        #[cfg(feature = "music-artist2")]
        "music-artist2-symbolic.svg",
        #[cfg(feature = "music-note")]
        "music-note-symbolic.svg",
        #[cfg(feature = "music-note-single")]
        "music-note-single-symbolic.svg",
        #[cfg(feature = "music-queue")]
        "music-queue-symbolic.svg",
        #[cfg(feature = "navigate")]
        "navigate-symbolic.svg",
        #[cfg(feature = "network-cellular-no-data-signal-excellent")]
        "network-cellular-no-data-signal-excellent-symbolic.svg",
        #[cfg(feature = "network-cellular-no-data-signal-good")]
        "network-cellular-no-data-signal-good-symbolic.svg",
        #[cfg(feature = "network-cellular-no-data-signal-none")]
        "network-cellular-no-data-signal-none-symbolic.svg",
        #[cfg(feature = "network-cellular-no-data-signal-ok")]
        "network-cellular-no-data-signal-ok-symbolic.svg",
        #[cfg(feature = "network-cellular-no-data-signal-weak")]
        "network-cellular-no-data-signal-weak-symbolic.svg",
        #[cfg(feature = "network-printer")]
        "network-printer-symbolic.svg",
        #[cfg(feature = "network-raid")]
        "network-raid-symbolic.svg",
        #[cfg(feature = "network-server")]
        "network-server-symbolic.svg",
        #[cfg(feature = "network-workgroup")]
        "network-workgroup-symbolic.svg",
        #[cfg(feature = "newspaper")]
        "newspaper-symbolic.svg",
        #[cfg(feature = "newspaper-rounded")]
        "newspaper-rounded-symbolic.svg",
        #[cfg(feature = "nintendo-controller")]
        "nintendo-controller-symbolic.svg",
        #[cfg(feature = "no-bed")]
        "no-bed-symbolic.svg",
        #[cfg(feature = "no-bluetooth")]
        "no-bluetooth-symbolic.svg",
        #[cfg(feature = "no-flying")]
        "no-flying-symbolic.svg",
        #[cfg(feature = "no-toilets")]
        "no-toilets-symbolic.svg",
        #[cfg(feature = "no-wheelchair")]
        "no-wheelchair-symbolic.svg",
        #[cfg(feature = "noodles")]
        "noodles-symbolic.svg",
        #[cfg(feature = "normalize")]
        "normalize-symbolic.svg",
        #[cfg(feature = "not-junk")]
        "not-junk-symbolic.svg",
        #[cfg(feature = "not-junk-alt")]
        "not-junk-alt-symbolic.svg",
        #[cfg(feature = "note")]
        "note-symbolic.svg",
        #[cfg(feature = "note2")]
        "note2-symbolic.svg",
        #[cfg(feature = "notepad")]
        "notepad-symbolic.svg",
        #[cfg(feature = "nudity")]
        "nudity-symbolic.svg",
        #[cfg(feature = "nudity-none")]
        "nudity-none-symbolic.svg",
        #[cfg(feature = "nut")]
        "nut-symbolic.svg",
        #[cfg(feature = "object-layout")]
        "object-layout-symbolic.svg",
        #[cfg(feature = "object-packing")]
        "object-packing-symbolic.svg",
        #[cfg(feature = "offline-globe")]
        "offline-globe-symbolic.svg",
        #[cfg(feature = "online")]
        "online-symbolic.svg",
        #[cfg(feature = "opacity")]
        "opacity-symbolic.svg",
        #[cfg(feature = "open-book")]
        "open-book-symbolic.svg",
        #[cfg(feature = "outbox")]
        "outbox-symbolic.svg",
        #[cfg(feature = "overlapping-windows")]
        "overlapping-windows-symbolic.svg",
        #[cfg(feature = "package")]
        "package-symbolic.svg",
        #[cfg(feature = "package-x-generic")]
        "package-x-generic-symbolic.svg",
        #[cfg(feature = "padlock")]
        "padlock-symbolic.svg",
        #[cfg(feature = "padlock-open")]
        "padlock-open-symbolic.svg",
        #[cfg(feature = "padlock2")]
        "padlock2-symbolic.svg",
        #[cfg(feature = "padlock2-open")]
        "padlock2-open-symbolic.svg",
        #[cfg(feature = "paintbrush")]
        "paintbrush-symbolic.svg",
        #[cfg(feature = "panorama-360")]
        "panorama-360-symbolic.svg",
        #[cfg(feature = "panorama-horizontal")]
        "panorama-horizontal-symbolic.svg",
        #[cfg(feature = "panorama-vertical")]
        "panorama-vertical-symbolic.svg",
        #[cfg(feature = "paper")]
        "paper-symbolic.svg",
        #[cfg(feature = "paper-filled")]
        "paper-filled-symbolic.svg",
        #[cfg(feature = "paper-plane")]
        "paper-plane-symbolic.svg",
        #[cfg(feature = "papyrus")]
        "papyrus-symbolic.svg",
        #[cfg(feature = "papyrus-vertical")]
        "papyrus-vertical-symbolic.svg",
        #[cfg(feature = "parent")]
        "parent-symbolic.svg",
        #[cfg(feature = "parking-sign")]
        "parking-sign-symbolic.svg",
        #[cfg(feature = "password-entry")]
        "password-entry-symbolic.svg",
        #[cfg(feature = "path-erase-delete")]
        "path-erase-delete-symbolic.svg",
        #[cfg(feature = "path-erase-split")]
        "path-erase-split-symbolic.svg",
        #[cfg(feature = "path-erase-split2")]
        "path-erase-split2-symbolic.svg",
        #[cfg(feature = "path-tool")]
        "path-tool-symbolic.svg",
        #[cfg(feature = "pause")]
        "pause-symbolic.svg",
        #[cfg(feature = "pause-large")]
        "pause-large-symbolic.svg",
        #[cfg(feature = "pci-card")]
        "pci-card-symbolic.svg",
        #[cfg(feature = "pda")]
        "pda-symbolic.svg",
        #[cfg(feature = "pencil")]
        "pencil-symbolic.svg",
        #[cfg(feature = "pencil-and-paper")]
        "pencil-and-paper-symbolic.svg",
        #[cfg(feature = "penguin")]
        "penguin-symbolic.svg",
        #[cfg(feature = "penguin-alt")]
        "penguin-alt-symbolic.svg",
        #[cfg(feature = "people")]
        "people-symbolic.svg",
        #[cfg(feature = "pepper")]
        "pepper-symbolic.svg",
        #[cfg(feature = "permissions-advertising")]
        "permissions-advertising-symbolic.svg",
        #[cfg(feature = "permissions-camera")]
        "permissions-camera-symbolic.svg",
        #[cfg(feature = "permissions-generic")]
        "permissions-generic-symbolic.svg",
        #[cfg(feature = "permissions-location")]
        "permissions-location-symbolic.svg",
        #[cfg(feature = "permissions-microphone")]
        "permissions-microphone-symbolic.svg",
        #[cfg(feature = "permissions-notifications")]
        "permissions-notifications-symbolic.svg",
        #[cfg(feature = "permissions-password")]
        "permissions-password-symbolic.svg",
        #[cfg(feature = "person")]
        "person-symbolic.svg",
        #[cfg(feature = "person2")]
        "person2-symbolic.svg",
        #[cfg(feature = "phone")]
        "phone-symbolic.svg",
        #[cfg(feature = "phone-disabled")]
        "phone-disabled-symbolic.svg",
        #[cfg(feature = "phone-oldschool")]
        "phone-oldschool-symbolic.svg",
        #[cfg(feature = "phone-vibrate")]
        "phone-vibrate-symbolic.svg",
        #[cfg(feature = "phonelink")]
        "phonelink-symbolic.svg",
        #[cfg(feature = "phonelink-delete")]
        "phonelink-delete-symbolic.svg",
        #[cfg(feature = "phonelink-lock")]
        "phonelink-lock-symbolic.svg",
        #[cfg(feature = "phonelink-off")]
        "phonelink-off-symbolic.svg",
        #[cfg(feature = "phonelink-ring")]
        "phonelink-ring-symbolic.svg",
        #[cfg(feature = "phonelink-setup")]
        "phonelink-setup-symbolic.svg",
        #[cfg(feature = "phonelink2")]
        "phonelink2-symbolic.svg",
        #[cfg(feature = "phonelink2-off")]
        "phonelink2-off-symbolic.svg",
        #[cfg(feature = "phosh")]
        "phosh-symbolic.svg",
        #[cfg(feature = "photo-camera")]
        "photo-camera-symbolic.svg",
        #[cfg(feature = "pin")]
        "pin-symbolic.svg",
        #[cfg(feature = "pin-location")]
        "pin-location-symbolic.svg",
        #[cfg(feature = "pip-in")]
        "pip-in-symbolic.svg",
        #[cfg(feature = "pip-out")]
        "pip-out-symbolic.svg",
        #[cfg(feature = "pipette")]
        "pipette-symbolic.svg",
        #[cfg(feature = "play")]
        "play-symbolic.svg",
        #[cfg(feature = "play-large")]
        "play-large-symbolic.svg",
        #[cfg(feature = "play-large-diabled")]
        "play-large-diabled-symbolic.svg",
        #[cfg(feature = "playback")]
        "playback-symbolic.svg",
        #[cfg(feature = "playback-error")]
        "playback-error-symbolic.svg",
        #[cfg(feature = "playback-options")]
        "playback-options-symbolic.svg",
        #[cfg(feature = "playback-speed")]
        "playback-speed-symbolic.svg",
        #[cfg(feature = "playlist")]
        "playlist-symbolic.svg",
        #[cfg(feature = "playlist2")]
        "playlist2-symbolic.svg",
        #[cfg(feature = "plus")]
        "plus-symbolic.svg",
        #[cfg(feature = "plus-large")]
        "plus-large-symbolic.svg",
        #[cfg(feature = "podcast")]
        "podcast-symbolic.svg",
        #[cfg(feature = "portal")]
        "portal-symbolic.svg",
        #[cfg(feature = "positive-feedback")]
        "positive-feedback-symbolic.svg",
        #[cfg(feature = "post-box")]
        "post-box-symbolic.svg",
        #[cfg(feature = "power")]
        "power-symbolic.svg",
        #[cfg(feature = "printer")]
        "printer-symbolic.svg",
        #[cfg(feature = "printer-network")]
        "printer-network-symbolic.svg",
        #[cfg(feature = "printer-round")]
        "printer-round-symbolic.svg",
        #[cfg(feature = "profit")]
        "profit-symbolic.svg",
        #[cfg(feature = "projector")]
        "projector-symbolic.svg",
        #[cfg(feature = "pub")]
        "pub-symbolic.svg",
        #[cfg(feature = "puzzle-piece")]
        "puzzle-piece-symbolic.svg",
        #[cfg(feature = "qr-code")]
        "qr-code-symbolic.svg",
        #[cfg(feature = "qr-code-scanner")]
        "qr-code-scanner-symbolic.svg",
        #[cfg(feature = "question")]
        "question-symbolic.svg",
        #[cfg(feature = "question-round")]
        "question-round-symbolic.svg",
        #[cfg(feature = "quotation")]
        "quotation-symbolic.svg",
        #[cfg(feature = "raid")]
        "raid-symbolic.svg",
        #[cfg(feature = "rain")]
        "rain-symbolic.svg",
        #[cfg(feature = "rain-alt")]
        "rain-alt-symbolic.svg",
        #[cfg(feature = "rain-outline")]
        "rain-outline-symbolic.svg",
        #[cfg(feature = "rain-scattered-outline")]
        "rain-scattered-outline-symbolic.svg",
        #[cfg(feature = "record-screen")]
        "record-screen-symbolic.svg",
        #[cfg(feature = "refresh")]
        "refresh-symbolic.svg",
        #[cfg(feature = "refresh-large")]
        "refresh-large-symbolic.svg",
        #[cfg(feature = "regex")]
        "regex-symbolic.svg",
        #[cfg(feature = "relm4")]
        "relm4-symbolic.svg",
        #[cfg(feature = "remote-terminal")]
        "remote-terminal-symbolic.svg",
        #[cfg(feature = "resize-mode")]
        "resize-mode-symbolic.svg",
        #[cfg(feature = "resources")]
        "resources-symbolic.svg",
        #[cfg(feature = "restaurant")]
        "restaurant-symbolic.svg",
        #[cfg(feature = "rich-text")]
        "rich-text-symbolic.svg",
        #[cfg(feature = "right")]
        "right-symbolic.svg",
        #[cfg(feature = "right-large")]
        "right-large-symbolic.svg",
        #[cfg(feature = "roll")]
        "roll-symbolic.svg",
        #[cfg(feature = "roll-vertical")]
        "roll-vertical-symbolic.svg",
        #[cfg(feature = "rotate")]
        "rotate-symbolic.svg",
        #[cfg(feature = "rotation-lock")]
        "rotation-lock-symbolic.svg",
        #[cfg(feature = "rotation-lock-disabled")]
        "rotation-lock-disabled-symbolic.svg",
        #[cfg(feature = "routing")]
        "routing-symbolic.svg",
        #[cfg(feature = "salami")]
        "salami-symbolic.svg",
        #[cfg(feature = "scale")]
        "scale-symbolic.svg",
        #[cfg(feature = "scales")]
        "scales-symbolic.svg",
        #[cfg(feature = "scales-detail")]
        "scales-detail-symbolic.svg",
        #[cfg(feature = "scanner")]
        "scanner-symbolic.svg",
        #[cfg(feature = "scattered-clouds")]
        "scattered-clouds-symbolic.svg",
        #[cfg(feature = "school")]
        "school-symbolic.svg",
        #[cfg(feature = "scissors")]
        "scissors-symbolic.svg",
        #[cfg(feature = "screen-privacy")]
        "screen-privacy-symbolic.svg",
        #[cfg(feature = "screen-privacy-disabled")]
        "screen-privacy-disabled-symbolic.svg",
        #[cfg(feature = "screen-privacy-disabled7")]
        "screen-privacy-disabled7-symbolic.svg",
        #[cfg(feature = "screen-privacy2")]
        "screen-privacy2-symbolic.svg",
        #[cfg(feature = "screen-privacy3")]
        "screen-privacy3-symbolic.svg",
        #[cfg(feature = "screen-privacy4")]
        "screen-privacy4-symbolic.svg",
        #[cfg(feature = "screen-privacy5")]
        "screen-privacy5-symbolic.svg",
        #[cfg(feature = "screen-privacy6")]
        "screen-privacy6-symbolic.svg",
        #[cfg(feature = "screen-privacy7")]
        "screen-privacy7-symbolic.svg",
        #[cfg(feature = "screen-privacy7-disabled")]
        "screen-privacy7-disabled-symbolic.svg",
        #[cfg(feature = "screencast-recorded")]
        "screencast-recorded-symbolic.svg",
        #[cfg(feature = "screenshooter")]
        "screenshooter-symbolic.svg",
        #[cfg(feature = "screenshot")]
        "screenshot-symbolic.svg",
        #[cfg(feature = "screenshot-recorded")]
        "screenshot-recorded-symbolic.svg",
        #[cfg(feature = "scroll")]
        "scroll-symbolic.svg",
        #[cfg(feature = "scroll-on-a-roll")]
        "scroll-on-a-roll-symbolic.svg",
        #[cfg(feature = "select")]
        "select-symbolic.svg",
        #[cfg(feature = "select-mode")]
        "select-mode-symbolic.svg",
        #[cfg(feature = "selection")]
        "selection-symbolic.svg",
        #[cfg(feature = "selection-opaque")]
        "selection-opaque-symbolic.svg",
        #[cfg(feature = "selection-opaque-2")]
        "selection-opaque-2-symbolic.svg",
        #[cfg(feature = "selection-opaque-3")]
        "selection-opaque-3-symbolic.svg",
        #[cfg(feature = "send")]
        "send-symbolic.svg",
        #[cfg(feature = "send-alt")]
        "send-alt-symbolic.svg",
        #[cfg(feature = "sentiment-dissatisfied")]
        "sentiment-dissatisfied-symbolic.svg",
        #[cfg(feature = "sentiment-neutral")]
        "sentiment-neutral-symbolic.svg",
        #[cfg(feature = "sentiment-satisfied")]
        "sentiment-satisfied-symbolic.svg",
        #[cfg(feature = "sentiment-very-dissatisfied")]
        "sentiment-very-dissatisfied-symbolic.svg",
        #[cfg(feature = "sentiment-very-satisfied")]
        "sentiment-very-satisfied-symbolic.svg",
        #[cfg(feature = "server-pick")]
        "server-pick-symbolic.svg",
        #[cfg(feature = "settings")]
        "settings-symbolic.svg",
        #[cfg(feature = "shapes")]
        "shapes-symbolic.svg",
        #[cfg(feature = "shapes-large")]
        "shapes-large-symbolic.svg",
        #[cfg(feature = "share")]
        "share-symbolic.svg",
        #[cfg(feature = "share-alt")]
        "share-alt-symbolic.svg",
        #[cfg(feature = "shear")]
        "shear-symbolic.svg",
        #[cfg(feature = "shell")]
        "shell-symbolic.svg",
        #[cfg(feature = "shell-overview")]
        "shell-overview-symbolic.svg",
        #[cfg(feature = "shield-danger")]
        "shield-danger-symbolic.svg",
        #[cfg(feature = "shield-safe")]
        "shield-safe-symbolic.svg",
        #[cfg(feature = "shield-warning")]
        "shield-warning-symbolic.svg",
        #[cfg(feature = "shift")]
        "shift-symbolic.svg",
        #[cfg(feature = "shoe-box")]
        "shoe-box-symbolic.svg",
        #[cfg(feature = "shopping-cart")]
        "shopping-cart-symbolic.svg",
        #[cfg(feature = "showers")]
        "showers-symbolic.svg",
        #[cfg(feature = "sidebar-toggle-left")]
        "sidebar-toggle-left-symbolic.svg",
        #[cfg(feature = "sidebar-toggle-right")]
        "sidebar-toggle-right-symbolic.svg",
        #[cfg(feature = "sign-language")]
        "sign-language-symbolic.svg",
        #[cfg(feature = "signature")]
        "signature-symbolic.svg",
        #[cfg(feature = "signature-bad")]
        "signature-bad-symbolic.svg",
        #[cfg(feature = "sim")]
        "sim-symbolic.svg",
        #[cfg(feature = "single-display")]
        "single-display-symbolic.svg",
        #[cfg(feature = "size-horizontally")]
        "size-horizontally-symbolic.svg",
        #[cfg(feature = "size-left")]
        "size-left-symbolic.svg",
        #[cfg(feature = "size-right")]
        "size-right-symbolic.svg",
        #[cfg(feature = "size-vertically")]
        "size-vertically-symbolic.svg",
        #[cfg(feature = "skip-backwards-10")]
        "skip-backwards-10-symbolic.svg",
        #[cfg(feature = "skip-backwards-30")]
        "skip-backwards-30-symbolic.svg",
        #[cfg(feature = "skip-forward-10")]
        "skip-forward-10-symbolic.svg",
        #[cfg(feature = "skip-forward-30")]
        "skip-forward-30-symbolic.svg",
        #[cfg(feature = "skull")]
        "skull-symbolic.svg",
        #[cfg(feature = "skull-small")]
        "skull-small-symbolic.svg",
        #[cfg(feature = "small-x")]
        "small-x-symbolic.svg",
        #[cfg(feature = "smartcard")]
        "smartcard-symbolic.svg",
        #[cfg(feature = "smartphone")]
        "smartphone-symbolic.svg",
        #[cfg(feature = "smile")]
        "smile-symbolic.svg",
        #[cfg(feature = "smoothen")]
        "smoothen-symbolic.svg",
        #[cfg(feature = "smudge-finger")]
        "smudge-finger-symbolic.svg",
        #[cfg(feature = "snap")]
        "snap-symbolic.svg",
        #[cfg(feature = "snapshots")]
        "snapshots-symbolic.svg",
        #[cfg(feature = "snapshots-alt")]
        "snapshots-alt-symbolic.svg",
        #[cfg(feature = "snow")]
        "snow-symbolic.svg",
        #[cfg(feature = "snow-outline")]
        "snow-outline-symbolic.svg",
        #[cfg(feature = "social-network")]
        "social-network-symbolic.svg",
        #[cfg(feature = "social-network-none")]
        "social-network-none-symbolic.svg",
        #[cfg(feature = "sonar")]
        "sonar-symbolic.svg",
        #[cfg(feature = "sound-wave")]
        "sound-wave-symbolic.svg",
        #[cfg(feature = "sound-wave-alt")]
        "sound-wave-alt-symbolic.svg",
        #[cfg(feature = "soundcard")]
        "soundcard-symbolic.svg",
        #[cfg(feature = "soup")]
        "soup-symbolic.svg",
        #[cfg(feature = "source-pick")]
        "source-pick-symbolic.svg",
        #[cfg(feature = "speakers")]
        "speakers-symbolic.svg",
        #[cfg(feature = "speedometer")]
        "speedometer-symbolic.svg",
        #[cfg(feature = "speedometer2")]
        "speedometer2-symbolic.svg",
        #[cfg(feature = "speedometer3")]
        "speedometer3-symbolic.svg",
        #[cfg(feature = "speedometer4")]
        "speedometer4-symbolic.svg",
        #[cfg(feature = "spinner")]
        "spinner-symbolic.svg",
        #[cfg(feature = "spring")]
        "spring-symbolic.svg",
        #[cfg(feature = "square-filled")]
        "square-filled-symbolic.svg",
        #[cfg(feature = "square-outline-thick")]
        "square-outline-thick-symbolic.svg",
        #[cfg(feature = "square-outline-thin")]
        "square-outline-thin-symbolic.svg",
        #[cfg(feature = "ssd")]
        "ssd-symbolic.svg",
        #[cfg(feature = "stacked-plates")]
        "stacked-plates-symbolic.svg",
        #[cfg(feature = "stamp")]
        "stamp-symbolic.svg",
        #[cfg(feature = "star-filled")]
        "star-filled-symbolic.svg",
        #[cfg(feature = "star-filled-rounded")]
        "star-filled-rounded-symbolic.svg",
        #[cfg(feature = "star-large")]
        "star-large-symbolic.svg",
        #[cfg(feature = "star-outline-half-left")]
        "star-outline-half-left-symbolic.svg",
        #[cfg(feature = "star-outline-half-right")]
        "star-outline-half-right-symbolic.svg",
        #[cfg(feature = "star-outline-rounded")]
        "star-outline-rounded-symbolic.svg",
        #[cfg(feature = "star-outline-thick")]
        "star-outline-thick-symbolic.svg",
        #[cfg(feature = "star-outline-thin")]
        "star-outline-thin-symbolic.svg",
        #[cfg(feature = "step-back")]
        "step-back-symbolic.svg",
        #[cfg(feature = "step-in")]
        "step-in-symbolic.svg",
        #[cfg(feature = "step-out")]
        "step-out-symbolic.svg",
        #[cfg(feature = "step-over")]
        "step-over-symbolic.svg",
        #[cfg(feature = "steps")]
        "steps-symbolic.svg",
        #[cfg(feature = "stop")]
        "stop-symbolic.svg",
        #[cfg(feature = "stop-large")]
        "stop-large-symbolic.svg",
        #[cfg(feature = "stop-sign")]
        "stop-sign-symbolic.svg",
        #[cfg(feature = "stop-sign-large")]
        "stop-sign-large-symbolic.svg",
        #[cfg(feature = "stopwatch")]
        "stopwatch-symbolic.svg",
        #[cfg(feature = "storm")]
        "storm-symbolic.svg",
        #[cfg(feature = "storm-outline")]
        "storm-outline-symbolic.svg",
        #[cfg(feature = "strong-language")]
        "strong-language-symbolic.svg",
        #[cfg(feature = "strong-language-none")]
        "strong-language-none-symbolic.svg",
        #[cfg(feature = "subtitles")]
        "subtitles-symbolic.svg",
        #[cfg(feature = "success")]
        "success-symbolic.svg",
        #[cfg(feature = "sun")]
        "sun-symbolic.svg",
        #[cfg(feature = "sun-alt")]
        "sun-alt-symbolic.svg",
        #[cfg(feature = "sun-outline")]
        "sun-outline-symbolic.svg",
        #[cfg(feature = "tab")]
        "tab-symbolic.svg",
        #[cfg(feature = "tab-new")]
        "tab-new-symbolic.svg",
        #[cfg(feature = "tab-new-filled")]
        "tab-new-filled-symbolic.svg",
        #[cfg(feature = "tab-new-large")]
        "tab-new-large-symbolic.svg",
        #[cfg(feature = "table")]
        "table-symbolic.svg",
        #[cfg(feature = "tablet")]
        "tablet-symbolic.svg",
        #[cfg(feature = "tabs-stack")]
        "tabs-stack-symbolic.svg",
        #[cfg(feature = "tag")]
        "tag-symbolic.svg",
        #[cfg(feature = "tape")]
        "tape-symbolic.svg",
        #[cfg(feature = "task")]
        "task-symbolic.svg",
        #[cfg(feature = "task-assigned")]
        "task-assigned-symbolic.svg",
        #[cfg(feature = "task-assigned-to")]
        "task-assigned-to-symbolic.svg",
        #[cfg(feature = "task-recurring")]
        "task-recurring-symbolic.svg",
        #[cfg(feature = "tea")]
        "tea-symbolic.svg",
        #[cfg(feature = "tennis")]
        "tennis-symbolic.svg",
        #[cfg(feature = "terminal")]
        "terminal-symbolic.svg",
        #[cfg(feature = "test")]
        "test-symbolic.svg",
        #[cfg(feature = "test-pass")]
        "test-pass-symbolic.svg",
        #[cfg(feature = "text")]
        "text-symbolic.svg",
        #[cfg(feature = "text-bold")]
        "text-bold-symbolic.svg",
        #[cfg(feature = "text-direction-ltr")]
        "text-direction-ltr-symbolic.svg",
        #[cfg(feature = "text-direction-rtl")]
        "text-direction-rtl-symbolic.svg",
        #[cfg(feature = "text-indent-less")]
        "text-indent-less-symbolic.svg",
        #[cfg(feature = "text-indent-more")]
        "text-indent-more-symbolic.svg",
        #[cfg(feature = "text-italic")]
        "text-italic-symbolic.svg",
        #[cfg(feature = "text-justify-center")]
        "text-justify-center-symbolic.svg",
        #[cfg(feature = "text-justify-fill")]
        "text-justify-fill-symbolic.svg",
        #[cfg(feature = "text-justify-left")]
        "text-justify-left-symbolic.svg",
        #[cfg(feature = "text-justify-right")]
        "text-justify-right-symbolic.svg",
        #[cfg(feature = "text-squiggly")]
        "text-squiggly-symbolic.svg",
        #[cfg(feature = "text-strikethrough")]
        "text-strikethrough-symbolic.svg",
        #[cfg(feature = "text-underline")]
        "text-underline-symbolic.svg",
        #[cfg(feature = "text2")]
        "text2-symbolic.svg",
        #[cfg(feature = "text3")]
        "text3-symbolic.svg",
        #[cfg(feature = "theater")]
        "theater-symbolic.svg",
        #[cfg(feature = "thumbs-down")]
        "thumbs-down-symbolic.svg",
        #[cfg(feature = "thumbs-up")]
        "thumbs-up-symbolic.svg",
        #[cfg(feature = "thunderbolt")]
        "thunderbolt-symbolic.svg",
        #[cfg(feature = "ticket")]
        "ticket-symbolic.svg",
        #[cfg(feature = "ticket-special")]
        "ticket-special-symbolic.svg",
        #[cfg(feature = "timer")]
        "timer-symbolic.svg",
        #[cfg(feature = "timer-sand")]
        "timer-sand-symbolic.svg",
        #[cfg(feature = "today")]
        "today-symbolic.svg",
        #[cfg(feature = "today-alt")]
        "today-alt-symbolic.svg",
        #[cfg(feature = "toilets")]
        "toilets-symbolic.svg",
        #[cfg(feature = "toolbars")]
        "toolbars-symbolic.svg",
        #[cfg(feature = "top")]
        "top-symbolic.svg",
        #[cfg(feature = "top-large")]
        "top-large-symbolic.svg",
        #[cfg(feature = "tornado")]
        "tornado-symbolic.svg",
        #[cfg(feature = "touchpad")]
        "touchpad-symbolic.svg",
        #[cfg(feature = "touchpad-disabled")]
        "touchpad-disabled-symbolic.svg",
        #[cfg(feature = "town")]
        "town-symbolic.svg",
        #[cfg(feature = "transform")]
        "transform-symbolic.svg",
        #[cfg(feature = "transparent-background")]
        "transparent-background-symbolic.svg",
        #[cfg(feature = "tree")]
        "tree-symbolic.svg",
        #[cfg(feature = "tree2")]
        "tree2-symbolic.svg",
        #[cfg(feature = "trophy")]
        "trophy-symbolic.svg",
        #[cfg(feature = "tty")]
        "tty-symbolic.svg",
        #[cfg(feature = "tv")]
        "tv-symbolic.svg",
        #[cfg(feature = "ungroup")]
        "ungroup-symbolic.svg",
        #[cfg(feature = "up")]
        "up-symbolic.svg",
        #[cfg(feature = "up-large")]
        "up-large-symbolic.svg",
        #[cfg(feature = "update")]
        "update-symbolic.svg",
        #[cfg(feature = "uppercase")]
        "uppercase-symbolic.svg",
        #[cfg(feature = "ups")]
        "ups-symbolic.svg",
        #[cfg(feature = "usb-stick")]
        "usb-stick-symbolic.svg",
        #[cfg(feature = "usb-stick-round")]
        "usb-stick-round-symbolic.svg",
        #[cfg(feature = "user-trash")]
        "user-trash-symbolic.svg",
        #[cfg(feature = "user-trash-full")]
        "user-trash-full-symbolic.svg",
        #[cfg(feature = "video-camera")]
        "video-camera-symbolic.svg",
        #[cfg(feature = "video-encoder")]
        "video-encoder-symbolic.svg",
        #[cfg(feature = "view-columns")]
        "view-columns-symbolic.svg",
        #[cfg(feature = "view-switcher")]
        "view-switcher-symbolic.svg",
        #[cfg(feature = "violence")]
        "violence-symbolic.svg",
        #[cfg(feature = "violence-none")]
        "violence-none-symbolic.svg",
        #[cfg(feature = "violence2")]
        "violence2-symbolic.svg",
        #[cfg(feature = "violence2-none")]
        "violence2-none-symbolic.svg",
        #[cfg(feature = "violence3")]
        "violence3-symbolic.svg",
        #[cfg(feature = "violence3-none")]
        "violence3-none-symbolic.svg",
        #[cfg(feature = "vpn-caps")]
        "vpn-caps-symbolic.svg",
        #[cfg(feature = "vpn-caps-disabled")]
        "vpn-caps-disabled-symbolic.svg",
        #[cfg(feature = "wacom")]
        "wacom-symbolic.svg",
        #[cfg(feature = "walking")]
        "walking-symbolic.svg",
        #[cfg(feature = "wallet")]
        "wallet-symbolic.svg",
        #[cfg(feature = "wallet2")]
        "wallet2-symbolic.svg",
        #[cfg(feature = "wallet3")]
        "wallet3-symbolic.svg",
        #[cfg(feature = "warning")]
        "warning-symbolic.svg",
        #[cfg(feature = "weather-alert")]
        "weather-alert-symbolic.svg",
        #[cfg(feature = "week")]
        "week-symbolic.svg",
        #[cfg(feature = "weight")]
        "weight-symbolic.svg",
        #[cfg(feature = "weight2")]
        "weight2-symbolic.svg",
        #[cfg(feature = "wheat")]
        "wheat-symbolic.svg",
        #[cfg(feature = "wheelchair")]
        "wheelchair-symbolic.svg",
        #[cfg(feature = "wheelchair-alt")]
        "wheelchair-alt-symbolic.svg",
        #[cfg(feature = "wheelchair-limited")]
        "wheelchair-limited-symbolic.svg",
        #[cfg(feature = "window")]
        "window-symbolic.svg",
        #[cfg(feature = "window-flat")]
        "window-flat-symbolic.svg",
        #[cfg(feature = "window-grow")]
        "window-grow-symbolic.svg",
        #[cfg(feature = "window-scrolling")]
        "window-scrolling-symbolic.svg",
        #[cfg(feature = "window-shrink")]
        "window-shrink-symbolic.svg",
        #[cfg(feature = "window-sound-source")]
        "window-sound-source-symbolic.svg",
        #[cfg(feature = "windy")]
        "windy-symbolic.svg",
        #[cfg(feature = "wine-glass")]
        "wine-glass-symbolic.svg",
        #[cfg(feature = "work-week")]
        "work-week-symbolic.svg",
        #[cfg(feature = "wrench")]
        "wrench-symbolic.svg",
        #[cfg(feature = "wrench-wide")]
        "wrench-wide-symbolic.svg",
        #[cfg(feature = "x-circular")]
        "x-circular-symbolic.svg",
        #[cfg(feature = "xbox-controller")]
        "xbox-controller-symbolic.svg",
        #[cfg(feature = "year")]
        "year-symbolic.svg",
        #[cfg(feature = "year-alt")]
        "year-alt-symbolic.svg",
        // END AUTOGENERATED
    ];

    let icons = icon_list
        .into_iter()
        .map(|icon| {
            let base_path = Path::new(ICONS);
            GResourceFileData::from_file(
                [PREFIX, icon].into_iter().collect(),
                base_path.join(icon).as_path(),
                true,
                &PreprocessOptions::xml_stripblanks(),
            )
            .unwrap()
        })
        .collect();

    let data = GResourceBuilder::from_file_data(icons).build().unwrap();

    let path = std::env::var("OUT_DIR").unwrap();
    let path: &std::path::Path = path.as_ref();
    std::fs::write(path.join(TARGET_FILE), data).unwrap();
}
